// Code generated by cmd/gen-dispatcher. DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"

	"kubikles/pkg/events"
	"kubikles/pkg/helm"
	"kubikles/pkg/k8s"
	"kubikles/pkg/server"
	"kubikles/pkg/terminal"
)

// AppMethodCaller implements server.MethodCaller using a direct switch dispatch,
// avoiding reflect.MethodByName to enable Go linker dead-code elimination (DCE).
type AppMethodCaller struct {
	app *App
}

// Compile-time interface check.
var _ server.MethodCaller = (*AppMethodCaller)(nil)

// NewAppMethodCaller creates a new switch-based method caller wrapping the App.
func NewAppMethodCaller(app *App) *AppMethodCaller {
	return &AppMethodCaller{app: app}
}

// unmarshalArg unmarshals a JSON argument into a value of type T.
// Returns the zero value if the argument index is out of range or nil.
func unmarshalArg[T any](args []json.RawMessage, index int) (T, error) {
	var v T
	if index >= len(args) || args[index] == nil {
		return v, nil
	}
	if err := json.Unmarshal(args[index], &v); err != nil {
		return v, fmt.Errorf("argument %d: %w", index, err)
	}
	return v, nil
}

// CallMethod dispatches a method call by name with JSON-encoded arguments.
func (c *AppMethodCaller) CallMethod(methodName string, args []json.RawMessage) (interface{}, error) {
	switch methodName {
	case "AddHelmRepository":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[int](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.AddHelmRepository(p0, p1, p2)
	case "AddPortForwardConfig":
		p0, err := unmarshalArg[PortForwardConfig](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.AddPortForwardConfig(p0)
		return result, err
	case "ApplyYAML":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.ApplyYAML(p0)
	case "CancelAIRequest":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.CancelAIRequest(p0)
		return nil, nil
	case "CancelConnectionTest":
		c.app.CancelConnectionTest()
		return nil, nil
	case "CancelListRequest":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return c.app.CancelListRequest(p0), nil
	case "CancelMetricsRequest":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return c.app.CancelMetricsRequest(p0), nil
	case "CheckAIProvider":
		return c.app.CheckAIProvider(), nil
	case "CheckRBACAccess":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[string](args, 6)
		if err != nil {
			return nil, err
		}
		p7, err := unmarshalArg[string](args, 7)
		if err != nil {
			return nil, err
		}
		result, err := c.app.CheckRBACAccess(p0, p1, p2, p3, p4, p5, p6, p7)
		return result, err
	case "ClearAISession":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return c.app.ClearAISession(p0), nil
	case "ClearAnthropicAPIKey":
		return nil, c.app.ClearAnthropicAPIKey()
	case "ClearPrometheusConfig":
		return nil, c.app.ClearPrometheusConfig()
	case "CloseAISession":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.CloseAISession(p0)
		return nil, nil
	case "CloseTerminalSession":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.CloseTerminalSession(p0)
	case "CollectIngressHostnames":
		p0, err := unmarshalArg[[]string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.CollectIngressHostnames(p0)
		return result, err
	case "ConfirmDialog":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return c.app.ConfirmDialog(p0, p1), nil
	case "CreateNodeDebugPod":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.CreateNodeDebugPod(p0, p1)
		return result, err
	case "CreatePodDirectory":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		return nil, c.app.CreatePodDirectory(p0, p1, p2, p3)
	case "DeleteCRD":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteCRD(p0)
	case "DeleteCSIDriver":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteCSIDriver(p0)
	case "DeleteCSINode":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteCSINode(p0)
	case "DeleteClusterRole":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteClusterRole(p0)
	case "DeleteClusterRoleBinding":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteClusterRoleBinding(p0)
	case "DeleteConfigMap":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteConfigMap(p0, p1)
	case "DeleteContext":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteContext(p0)
	case "DeleteCronJob":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteCronJob(p0, p1)
	case "DeleteCustomResource":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteCustomResource(p0, p1, p2, p3, p4)
	case "DeleteDaemonSet":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteDaemonSet(p0, p1)
	case "DeleteDeployment":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteDeployment(p0, p1)
	case "DeleteEndpointSlice":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteEndpointSlice(p0, p1)
	case "DeleteEndpoints":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteEndpoints(p0, p1)
	case "DeleteEvent":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteEvent(p0, p1)
	case "DeleteHPA":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteHPA(p0, p1)
	case "DeleteIngress":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteIngress(p0, p1)
	case "DeleteIngressClass":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteIngressClass(p0)
	case "DeleteJob":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteJob(p0, p1)
	case "DeleteLease":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteLease(p0, p1)
	case "DeleteLimitRange":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteLimitRange(p0, p1)
	case "DeleteMutatingWebhookConfiguration":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteMutatingWebhookConfiguration(p0)
	case "DeleteNamespace":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteNamespace(p0)
	case "DeleteNetworkPolicy":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteNetworkPolicy(p0, p1)
	case "DeleteNode":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteNode(p0)
	case "DeletePDB":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeletePDB(p0, p1)
	case "DeletePV":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeletePV(p0)
	case "DeletePVC":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeletePVC(p0, p1)
	case "DeletePod":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeletePod(p0, p1)
	case "DeletePodFile":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeletePodFile(p0, p1, p2, p3)
	case "DeletePortForwardConfig":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeletePortForwardConfig(p0)
	case "DeletePriorityClass":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeletePriorityClass(p0)
	case "DeleteReplicaSet":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteReplicaSet(p0, p1)
	case "DeleteResourceQuota":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteResourceQuota(p0, p1)
	case "DeleteRole":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteRole(p0, p1)
	case "DeleteRoleBinding":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteRoleBinding(p0, p1)
	case "DeleteSecret":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteSecret(p0, p1)
	case "DeleteService":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteService(p0, p1)
	case "DeleteServiceAccount":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteServiceAccount(p0, p1)
	case "DeleteStatefulSet":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteStatefulSet(p0, p1)
	case "DeleteStorageClass":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteStorageClass(p0)
	case "DeleteValidatingWebhookConfiguration":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DeleteValidatingWebhookConfiguration(p0)
	case "DetectIngressController":
		result, err := c.app.DetectIngressController()
		return result, err
	case "DetectPrometheus":
		result, err := c.app.DetectPrometheus()
		return result, err
	case "DiffResources":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[string](args, 6)
		if err != nil {
			return nil, err
		}
		p7, err := unmarshalArg[string](args, 7)
		if err != nil {
			return nil, err
		}
		p8, err := unmarshalArg[[]string](args, 8)
		if err != nil {
			return nil, err
		}
		result, err := c.app.DiffResources(p0, p1, p2, p3, p4, p5, p6, p7, p8)
		return result, err
	case "DownloadPodFile":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DownloadPodFile(p0, p1, p2, p3)
	case "DownloadPodFiles":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[[]string](args, 4)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DownloadPodFiles(p0, p1, p2, p3, p4)
	case "DownloadPodFolder":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		return nil, c.app.DownloadPodFolder(p0, p1, p2, p3)
	case "EvictPod":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.EvictPod(p0, p1)
	case "ExpandDependencyNode":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[int](args, 4)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ExpandDependencyNode(p0, p1, p2, p3, p4)
		return result, err
	case "ForceDeletePod":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.ForceDeletePod(p0, p1)
	case "ForceHelmReleaseStatus":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.ForceHelmReleaseStatus(p0, p1, p2)
	case "GetAIModels":
		return c.app.GetAIModels(), nil
	case "GetAIProviders":
		return c.app.GetAIProviders(), nil
	case "GetActivePortForwards":
		return c.app.GetActivePortForwards(), nil
	case "GetAllCertificateInfo":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetAllCertificateInfo(p0)
		return result, err
	case "GetAllContainersLogs":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[[]string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetAllContainersLogs(p0, p1, p2, p3, p4, p5)
		return result, err
	case "GetAllContainersLogsAfter":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[[]string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[int](args, 6)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetAllContainersLogsAfter(p0, p1, p2, p3, p4, p5, p6)
		return result, err
	case "GetAllContainersLogsAll":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[[]string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetAllContainersLogsAll(p0, p1, p2, p3, p4)
		return result, err
	case "GetAllContainersLogsBefore":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[[]string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[int](args, 6)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetAllContainersLogsBefore(p0, p1, p2, p3, p4, p5, p6)
		return result, err
	case "GetAllContainersLogsFromStart":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[[]string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetAllContainersLogsFromStart(p0, p1, p2, p3, p4)
		return result, err
	case "GetAllPodLogs":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetAllPodLogs(p0, p1, p2, p3, p4)
		return result, err
	case "GetAllPodsLogs":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[[]PodContainerPair](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[bool](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetAllPodsLogs(p0, p1, p2, p3, p4, p5)
		return result, err
	case "GetAllPodsLogsAfter":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[[]PodContainerPair](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[bool](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[int](args, 6)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetAllPodsLogsAfter(p0, p1, p2, p3, p4, p5, p6)
		return result, err
	case "GetAllPodsLogsAll":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[[]PodContainerPair](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[bool](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetAllPodsLogsAll(p0, p1, p2, p3, p4)
		return result, err
	case "GetAllPodsLogsBefore":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[[]PodContainerPair](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[bool](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[int](args, 6)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetAllPodsLogsBefore(p0, p1, p2, p3, p4, p5, p6)
		return result, err
	case "GetAllPodsLogsFromStart":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[[]PodContainerPair](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[bool](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetAllPodsLogsFromStart(p0, p1, p2, p3, p4)
		return result, err
	case "GetAnthropicAPIKeyStatus":
		return c.app.GetAnthropicAPIKeyStatus(), nil
	case "GetAvailablePort":
		p0, err := unmarshalArg[int](args, 0)
		if err != nil {
			return nil, err
		}
		return c.app.GetAvailablePort(p0), nil
	case "GetCRDPrinterColumns":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetCRDPrinterColumns(p0)
		return result, err
	case "GetCRDYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetCRDYaml(p0)
		return result, err
	case "GetCSIDriverYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetCSIDriverYaml(p0)
		return result, err
	case "GetCSINodeYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetCSINodeYaml(p0)
		return result, err
	case "GetCachedPrometheusConfig":
		return c.app.GetCachedPrometheusConfig(), nil
	case "GetCertificateInfo":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetCertificateInfo(p0)
		return result, err
	case "GetClusterRoleBindingYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetClusterRoleBindingYaml(p0)
		return result, err
	case "GetClusterRoleYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetClusterRoleYaml(p0)
		return result, err
	case "GetConfigMapData":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetConfigMapData(p0, p1)
		return result, err
	case "GetConfigMapYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetConfigMapYaml(p0, p1)
		return result, err
	case "GetContextDetails":
		result, err := c.app.GetContextDetails()
		return result, err
	case "GetControllerMetricsHistory":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[int](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[string](args, 6)
		if err != nil {
			return nil, err
		}
		p7, err := unmarshalArg[string](args, 7)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetControllerMetricsHistory(p0, p1, p2, p3, p4, p5, p6, p7)
		return result, err
	case "GetControllerMetricsHistoryRange":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[int](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[string](args, 6)
		if err != nil {
			return nil, err
		}
		p7, err := unmarshalArg[int64](args, 7)
		if err != nil {
			return nil, err
		}
		p8, err := unmarshalArg[int64](args, 8)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetControllerMetricsHistoryRange(p0, p1, p2, p3, p4, p5, p6, p7, p8)
		return result, err
	case "GetCrashLogPath":
		return c.app.GetCrashLogPath(), nil
	case "GetCronJobYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetCronJobYaml(p0, p1)
		return result, err
	case "GetCurrentContext":
		return c.app.GetCurrentContext(), nil
	case "GetCurrentTheme":
		return c.app.GetCurrentTheme(), nil
	case "GetCustomResourceEvents":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetCustomResourceEvents(p0, p1, p2, p3, p4, p5)
		return result, err
	case "GetCustomResourceYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetCustomResourceYaml(p0, p1, p2, p3, p4)
		return result, err
	case "GetDaemonSetYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetDaemonSetYaml(p0, p1)
		return result, err
	case "GetDebugClusterConfig":
		return c.app.GetDebugClusterConfig(), nil
	case "GetDeploymentYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetDeploymentYaml(p0, p1)
		return result, err
	case "GetEmbeddedBrowserStatus":
		return c.app.GetEmbeddedBrowserStatus(), nil
	case "GetEndpointSliceYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetEndpointSliceYaml(p0, p1)
		return result, err
	case "GetEndpointsYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetEndpointsYaml(p0, p1)
		return result, err
	case "GetEventYAML":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetEventYAML(p0, p1)
		return result, err
	case "GetFlowTimeline":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[int](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetFlowTimeline(p0, p1, p2, p3, p4)
		return result, err
	case "GetHPAYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetHPAYaml(p0, p1)
		return result, err
	case "GetHelmChartVersions":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetHelmChartVersions(p0, p1)
		return result, err
	case "GetHelmRelease":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetHelmRelease(p0, p1)
		return result, err
	case "GetHelmReleaseAllValues":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetHelmReleaseAllValues(p0, p1)
		return result, err
	case "GetHelmReleaseHistory":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetHelmReleaseHistory(p0, p1)
		return result, err
	case "GetHelmReleaseResources":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetHelmReleaseResources(p0, p1)
		return result, err
	case "GetHelmReleaseValues":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetHelmReleaseValues(p0, p1)
		return result, err
	case "GetIngressClassYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetIngressClassYaml(p0)
		return result, err
	case "GetIngressForwardState":
		return c.app.GetIngressForwardState(), nil
	case "GetIngressYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetIngressYaml(p0, p1)
		return result, err
	case "GetIssueRulesDir":
		return c.app.GetIssueRulesDir(), nil
	case "GetJobYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetJobYaml(p0, p1)
		return result, err
	case "GetK8sInitError":
		return c.app.GetK8sInitError(), nil
	case "GetLeaseYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetLeaseYaml(p0, p1)
		return result, err
	case "GetLimitRangeYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetLimitRangeYaml(p0, p1)
		return result, err
	case "GetListRequestStats":
		return c.app.GetListRequestStats(), nil
	case "GetManagedHosts":
		result, err := c.app.GetManagedHosts()
		return result, err
	case "GetMetricsEventMarkers":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetMetricsEventMarkers(p0, p1, p2, p3)
		return result, err
	case "GetMetricsRequestStats":
		return c.app.GetMetricsRequestStats(), nil
	case "GetMultiPodLogs":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[map[string]string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[[]string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[int64](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[int64](args, 5)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetMultiPodLogs(p0, p1, p2, p3, p4, p5)
		return result, err
	case "GetMutatingWebhookConfigurationYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetMutatingWebhookConfigurationYaml(p0)
		return result, err
	case "GetNamespaceMetricsHistory":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[int](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetNamespaceMetricsHistory(p0, p1, p2, p3, p4, p5)
		return result, err
	case "GetNamespaceMetricsHistoryRange":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[int](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[int64](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[int64](args, 6)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetNamespaceMetricsHistoryRange(p0, p1, p2, p3, p4, p5, p6)
		return result, err
	case "GetNamespaceResourceCounts":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetNamespaceResourceCounts(p0)
		return result, err
	case "GetNamespaceYAML":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetNamespaceYAML(p0)
		return result, err
	case "GetNetworkPolicyYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetNetworkPolicyYaml(p0, p1)
		return result, err
	case "GetNodeMetrics":
		result, err := c.app.GetNodeMetrics()
		return result, err
	case "GetNodeMetricsFromPrometheus":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[int](args, 2)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetNodeMetricsFromPrometheus(p0, p1, p2)
		return result, err
	case "GetNodeMetricsHistory":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[int](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetNodeMetricsHistory(p0, p1, p2, p3, p4, p5)
		return result, err
	case "GetNodeMetricsHistoryRange":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[int](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[int64](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[int64](args, 6)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetNodeMetricsHistoryRange(p0, p1, p2, p3, p4, p5, p6)
		return result, err
	case "GetNodeYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetNodeYaml(p0)
		return result, err
	case "GetPDBYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetPDBYaml(p0, p1)
		return result, err
	case "GetPVCYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetPVCYaml(p0, p1)
		return result, err
	case "GetPVYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetPVYaml(p0)
		return result, err
	case "GetPerformanceMetrics":
		return c.app.GetPerformanceMetrics(), nil
	case "GetPodEvictionInfo":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetPodEvictionInfo(p0, p1)
		return result, err
	case "GetPodLogs":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetPodLogs(p0, p1, p2, p3, p4, p5)
		return result, err
	case "GetPodLogsAfter":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[int](args, 6)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetPodLogsAfter(p0, p1, p2, p3, p4, p5, p6)
		return result, err
	case "GetPodLogsBefore":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[int](args, 6)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetPodLogsBefore(p0, p1, p2, p3, p4, p5, p6)
		return result, err
	case "GetPodLogsFromStart":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[bool](args, 4)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetPodLogsFromStart(p0, p1, p2, p3, p4)
		return result, err
	case "GetPodMetrics":
		result, err := c.app.GetPodMetrics()
		return result, err
	case "GetPodMetricsFromPrometheus":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[int](args, 2)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetPodMetricsFromPrometheus(p0, p1, p2)
		return result, err
	case "GetPodMetricsHistory":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[int](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[string](args, 6)
		if err != nil {
			return nil, err
		}
		p7, err := unmarshalArg[string](args, 7)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetPodMetricsHistory(p0, p1, p2, p3, p4, p5, p6, p7)
		return result, err
	case "GetPodMetricsHistoryRange":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[int](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[string](args, 6)
		if err != nil {
			return nil, err
		}
		p7, err := unmarshalArg[int64](args, 7)
		if err != nil {
			return nil, err
		}
		p8, err := unmarshalArg[int64](args, 8)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetPodMetricsHistoryRange(p0, p1, p2, p3, p4, p5, p6, p7, p8)
		return result, err
	case "GetPodPorts":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetPodPorts(p0, p1)
		return result, err
	case "GetPodYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetPodYaml(p0, p1)
		return result, err
	case "GetPortForwardConfigs":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return c.app.GetPortForwardConfigs(p0), nil
	case "GetPriorityClassYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetPriorityClassYaml(p0)
		return result, err
	case "GetRandomAvailablePort":
		return c.app.GetRandomAvailablePort(), nil
	case "GetReplicaSetYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetReplicaSetYaml(p0, p1)
		return result, err
	case "GetResourceDependencies":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetResourceDependencies(p0, p1, p2)
		return result, err
	case "GetResourceQuotaYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetResourceQuotaYaml(p0, p1)
		return result, err
	case "GetRoleBindingYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetRoleBindingYaml(p0, p1)
		return result, err
	case "GetRoleYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetRoleYaml(p0, p1)
		return result, err
	case "GetSecretData":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetSecretData(p0, p1)
		return result, err
	case "GetSecretYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetSecretYaml(p0, p1)
		return result, err
	case "GetServiceAccountYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetServiceAccountYaml(p0, p1)
		return result, err
	case "GetServicePorts":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetServicePorts(p0, p1)
		return result, err
	case "GetServiceYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetServiceYaml(p0, p1)
		return result, err
	case "GetStatefulSetYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetStatefulSetYaml(p0, p1)
		return result, err
	case "GetStorageClass":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetStorageClass(p0)
		return result, err
	case "GetStorageClassYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetStorageClassYaml(p0)
		return result, err
	case "GetThemes":
		return c.app.GetThemes(), nil
	case "GetThemesDir":
		return c.app.GetThemesDir(), nil
	case "GetToolDiscovery":
		return c.app.GetToolDiscovery(), nil
	case "GetValidatingWebhookConfigurationYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.GetValidatingWebhookConfigurationYaml(p0)
		return result, err
	case "GetVersionInfo":
		return c.app.GetVersionInfo(), nil
	case "HelmDryRunUpgrade":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[helm.UpgradeOptions](args, 2)
		if err != nil {
			return nil, err
		}
		result, err := c.app.HelmDryRunUpgrade(p0, p1, p2)
		return result, err
	case "HelmTemplateRelease":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[helm.UpgradeOptions](args, 2)
		if err != nil {
			return nil, err
		}
		result, err := c.app.HelmTemplateRelease(p0, p1, p2)
		return result, err
	case "HelmValidateValues":
		p0, err := unmarshalArg[helm.UpgradeOptions](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.HelmValidateValues(p0)
		return result, err
	case "IsDebugClusterEnabled":
		return c.app.IsDebugClusterEnabled(), nil
	case "IsHelmAvailable":
		return c.app.IsHelmAvailable(), nil
	case "IsRequestCancellationEnabled":
		return c.app.IsRequestCancellationEnabled(), nil
	case "ListCRDs":
		result, err := c.app.ListCRDs()
		return result, err
	case "ListCSIDrivers":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListCSIDrivers(p0)
		return result, err
	case "ListCSINodes":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListCSINodes(p0)
		return result, err
	case "ListChartSources":
		result, err := c.app.ListChartSources()
		return result, err
	case "ListClusterRoleBindings":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListClusterRoleBindings(p0)
		return result, err
	case "ListClusterRoles":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListClusterRoles(p0)
		return result, err
	case "ListConfigMaps":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListConfigMaps(p0, p1)
		return result, err
	case "ListContexts":
		result, err := c.app.ListContexts()
		return result, err
	case "ListCronJobs":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListCronJobs(p0, p1)
		return result, err
	case "ListCustomResources":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListCustomResources(p0, p1, p2, p3, p4)
		return result, err
	case "ListDaemonSets":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListDaemonSets(p0, p1)
		return result, err
	case "ListDeployments":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListDeployments(p0, p1)
		return result, err
	case "ListDeploymentsForContext":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListDeploymentsForContext(p0, p1)
		return result, err
	case "ListEndpointSlices":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListEndpointSlices(p0, p1)
		return result, err
	case "ListEndpoints":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListEndpoints(p0, p1)
		return result, err
	case "ListEvents":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListEvents(p0, p1)
		return result, err
	case "ListHPAs":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListHPAs(p0, p1)
		return result, err
	case "ListHelmReleases":
		p0, err := unmarshalArg[[]string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListHelmReleases(p0)
		return result, err
	case "ListHelmRepositories":
		result, err := c.app.ListHelmRepositories()
		return result, err
	case "ListIngressClasses":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListIngressClasses(p0)
		return result, err
	case "ListIngresses":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListIngresses(p0, p1)
		return result, err
	case "ListIssueRules":
		return c.app.ListIssueRules(), nil
	case "ListJobs":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListJobs(p0, p1)
		return result, err
	case "ListLeases":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListLeases(p0, p1)
		return result, err
	case "ListLimitRanges":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListLimitRanges(p0, p1)
		return result, err
	case "ListMutatingWebhookConfigurations":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListMutatingWebhookConfigurations(p0)
		return result, err
	case "ListNamespaces":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListNamespaces(p0)
		return result, err
	case "ListNamespacesForContext":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListNamespacesForContext(p0)
		return result, err
	case "ListNetworkPolicies":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListNetworkPolicies(p0, p1)
		return result, err
	case "ListNodes":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListNodes(p0)
		return result, err
	case "ListOCIRegistries":
		result, err := c.app.ListOCIRegistries()
		return result, err
	case "ListPDBs":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListPDBs(p0, p1)
		return result, err
	case "ListPVCs":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListPVCs(p0, p1)
		return result, err
	case "ListPVs":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListPVs(p0)
		return result, err
	case "ListPodFiles":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListPodFiles(p0, p1, p2, p3)
		return result, err
	case "ListPods":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListPods(p0, p1)
		return result, err
	case "ListPodsForContext":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListPodsForContext(p0, p1)
		return result, err
	case "ListPodsForNode":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListPodsForNode(p0)
		return result, err
	case "ListPriorityClasses":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListPriorityClasses(p0)
		return result, err
	case "ListPrometheusInstalls":
		result, err := c.app.ListPrometheusInstalls()
		return result, err
	case "ListReplicaSets":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListReplicaSets(p0, p1)
		return result, err
	case "ListResourceNamesForContext":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListResourceNamesForContext(p0, p1, p2)
		return result, err
	case "ListResourceQuotas":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListResourceQuotas(p0, p1)
		return result, err
	case "ListRoleBindings":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListRoleBindings(p0, p1)
		return result, err
	case "ListRoles":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListRoles(p0, p1)
		return result, err
	case "ListSecrets":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListSecrets(p0, p1)
		return result, err
	case "ListSecretsMetadata":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListSecretsMetadata(p0, p1)
		return result, err
	case "ListServiceAccounts":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListServiceAccounts(p0, p1)
		return result, err
	case "ListServices":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListServices(p0, p1)
		return result, err
	case "ListStatefulSets":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListStatefulSets(p0, p1)
		return result, err
	case "ListStorageClasses":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListStorageClasses(p0)
		return result, err
	case "ListValidatingWebhookConfigurations":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ListValidatingWebhookConfigurations(p0)
		return result, err
	case "LogDebug":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.LogDebug(p0)
		return nil, nil
	case "LogMessage":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.LogMessage(p0)
		return nil, nil
	case "LoginACRWithAzureCLI":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.LoginACRWithAzureCLI(p0)
	case "LoginOCIRegistry":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.LoginOCIRegistry(p0, p1, p2)
	case "LogoutOCIRegistry":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.LogoutOCIRegistry(p0)
	case "OpenCrashLogDir":
		return nil, c.app.OpenCrashLogDir()
	case "OpenIssueRulesDir":
		return nil, c.app.OpenIssueRulesDir()
	case "OpenThemesDir":
		return nil, c.app.OpenThemesDir()
	case "RefreshIngressHostnames":
		p0, err := unmarshalArg[[]string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.RefreshIngressHostnames(p0)
	case "ReloadIssueRules":
		return c.app.ReloadIssueRules(), nil
	case "ReloadThemes":
		return c.app.ReloadThemes(), nil
	case "RemoveHelmRepository":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.RemoveHelmRepository(p0)
	case "RemoveOCIRegistry":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.RemoveOCIRegistry(p0)
	case "RenameContext":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.RenameContext(p0, p1)
	case "ResetDebugCluster":
		return nil, c.app.ResetDebugCluster()
	case "ResizePVC":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.ResizePVC(p0, p1, p2)
	case "ResizeTerminal":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[int](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[int](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.ResizeTerminal(p0, p1, p2)
	case "ResolveTopLevelOwner":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		result, err := c.app.ResolveTopLevelOwner(p0, p1, p2)
		return result, err
	case "RestartDaemonSet":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.RestartDaemonSet(p0, p1)
	case "RestartDeployment":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.RestartDeployment(p0, p1)
	case "RestartStatefulSet":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.RestartStatefulSet(p0, p1)
	case "RollbackHelmRelease":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[int](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.RollbackHelmRelease(p0, p1, p2)
	case "RunIssueScan":
		p0, err := unmarshalArg[[]string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[[]string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[[]string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		result, err := c.app.RunIssueScan(p0, p1, p2, p3)
		return result, err
	case "SaveDebugLogs":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SaveDebugLogs(p0, p1)
	case "SaveLogFile":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SaveLogFile(p0)
	case "SaveLogsBundle":
		p0, err := unmarshalArg[[]PodLogEntry](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SaveLogsBundle(p0, p1)
	case "SavePodLogs":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SavePodLogs(p0, p1)
	case "SavePrometheusConfig":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[int](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SavePrometheusConfig(p0, p1, p2)
	case "SaveYamlBackup":
		p0, err := unmarshalArg[[]YamlBackupEntry](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SaveYamlBackup(p0, p1)
	case "ScaleDeployment":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[int32](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.ScaleDeployment(p0, p1, p2)
	case "ScaleReplicaSet":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[int32](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.ScaleReplicaSet(p0, p1, p2)
	case "ScaleStatefulSet":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[int32](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.ScaleStatefulSet(p0, p1, p2)
	case "SearchChartInSource":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		result, err := c.app.SearchChartInSource(p0, p1)
		return result, err
	case "SearchHelmChart":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.SearchHelmChart(p0)
		return result, err
	case "SelectKubeconfigFile":
		result, err := c.app.SelectKubeconfigFile()
		return result, err
	case "SendAIMessage":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[[]string](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[[]string](args, 5)
		if err != nil {
			return nil, err
		}
		p6, err := unmarshalArg[int](args, 6)
		if err != nil {
			return nil, err
		}
		return c.app.SendAIMessage(p0, p1, p2, p3, p4, p5, p6), nil
	case "SendTerminalInput":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SendTerminalInput(p0, p1)
	case "SendTextToEmbeddedBrowser":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SendTextToEmbeddedBrowser(p0)
	case "SetAnthropicAPIKey":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SetAnthropicAPIKey(p0)
	case "SetClientPoolSize":
		p0, err := unmarshalArg[int](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.SetClientPoolSize(p0)
		return nil, nil
	case "SetDebugClusterConfig":
		p0, err := unmarshalArg[k8s.DebugClusterConfig](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SetDebugClusterConfig(p0)
	case "SetDebugEnabled":
		p0, err := unmarshalArg[bool](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.SetDebugEnabled(p0)
		return nil, nil
	case "SetEmitter":
		p0, err := unmarshalArg[events.Emitter](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.SetEmitter(p0)
		return nil, nil
	case "SetEventCoalescerFrameInterval":
		p0, err := unmarshalArg[int](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.SetEventCoalescerFrameInterval(p0)
		return nil, nil
	case "SetExtraKubeconfigPaths":
		p0, err := unmarshalArg[[]string](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.SetExtraKubeconfigPaths(p0)
		return nil, nil
	case "SetForceHTTP1":
		p0, err := unmarshalArg[bool](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.SetForceHTTP1(p0)
		return nil, nil
	case "SetHelmRepositoryPriority":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[int](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SetHelmRepositoryPriority(p0, p1)
	case "SetK8sAPITimeout":
		p0, err := unmarshalArg[int](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.SetK8sAPITimeout(p0)
		return nil, nil
	case "SetNodeSchedulable":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[bool](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SetNodeSchedulable(p0, p1)
	case "SetOCIRegistryPriority":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[int](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SetOCIRegistryPriority(p0, p1)
	case "SetRequestCancellationEnabled":
		p0, err := unmarshalArg[bool](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.SetRequestCancellationEnabled(p0)
		return nil, nil
	case "SetTheme":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SetTheme(p0)
	case "StartAISession":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return c.app.StartAISession(p0), nil
	case "StartAllContainersLogStream":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[[]string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		result, err := c.app.StartAllContainersLogStream(p0, p1, p2, p3)
		return result, err
	case "StartAllPodsLogStream":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[[]PodContainerPair](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[bool](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		result, err := c.app.StartAllPodsLogStream(p0, p1, p2, p3)
		return result, err
	case "StartAutoStartPortForwards":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.StartAutoStartPortForwards(p0)
		return nil, nil
	case "StartEmbeddedBrowser":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.StartEmbeddedBrowser(p0)
		return result, err
	case "StartIngressForward":
		p0, err := unmarshalArg[IngressController](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[[]string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.StartIngressForward(p0, p1)
	case "StartLogStream":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[bool](args, 3)
		if err != nil {
			return nil, err
		}
		result, err := c.app.StartLogStream(p0, p1, p2, p3)
		return result, err
	case "StartPortForward":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.StartPortForward(p0)
	case "StartTerminalSession":
		p0, err := unmarshalArg[terminal.SessionOptions](args, 0)
		if err != nil {
			return nil, err
		}
		result, err := c.app.StartTerminalSession(p0)
		return result, err
	case "StopAllPortForwards":
		c.app.StopAllPortForwards()
		return nil, nil
	case "StopAllWatchers":
		c.app.StopAllWatchers()
		return nil, nil
	case "StopEmbeddedBrowser":
		return nil, c.app.StopEmbeddedBrowser()
	case "StopIngressForward":
		return nil, c.app.StopIngressForward()
	case "StopLogStream":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.StopLogStream(p0)
		return nil, nil
	case "StopPortForward":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.StopPortForward(p0)
	case "SubscribeCRDWatcher":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		return c.app.SubscribeCRDWatcher(p0, p1, p2, p3), nil
	case "SubscribeResourceWatcher":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return c.app.SubscribeResourceWatcher(p0, p1), nil
	case "SuspendCronJob":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[bool](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SuspendCronJob(p0, p1, p2)
	case "SwitchContext":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.SwitchContext(p0)
	case "TestConnection":
		p0, err := unmarshalArg[int](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.TestConnection(p0)
	case "TestCrash":
		p0, err := unmarshalArg[bool](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.TestCrash(p0)
		return nil, nil
	case "TestEmit":
		c.app.TestEmit()
		return nil, nil
	case "TestPrometheusEndpoint":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[int](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.TestPrometheusEndpoint(p0, p1, p2)
	case "TriggerCronJob":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.TriggerCronJob(p0, p1)
	case "UninstallHelmRelease":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UninstallHelmRelease(p0, p1)
	case "UnsubscribeWatcher":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		c.app.UnsubscribeWatcher(p0)
		return nil, nil
	case "UpdateAllHelmRepositories":
		return nil, c.app.UpdateAllHelmRepositories()
	case "UpdateCRDYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateCRDYaml(p0, p1)
	case "UpdateCSIDriverYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateCSIDriverYaml(p0, p1)
	case "UpdateCSINodeYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateCSINodeYaml(p0, p1)
	case "UpdateClusterRoleBindingYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateClusterRoleBindingYaml(p0, p1)
	case "UpdateClusterRoleYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateClusterRoleYaml(p0, p1)
	case "UpdateConfigMapData":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[map[string]string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateConfigMapData(p0, p1, p2)
	case "UpdateConfigMapYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateConfigMapYaml(p0, p1, p2)
	case "UpdateCronJobYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateCronJobYaml(p0, p1, p2)
	case "UpdateCustomResourceYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		p5, err := unmarshalArg[string](args, 5)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateCustomResourceYaml(p0, p1, p2, p3, p4, p5)
	case "UpdateDaemonSetYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateDaemonSetYaml(p0, p1, p2)
	case "UpdateDeploymentYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateDeploymentYaml(p0, p1, p2)
	case "UpdateEndpointSliceYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateEndpointSliceYaml(p0, p1, p2)
	case "UpdateEndpointsYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateEndpointsYaml(p0, p1, p2)
	case "UpdateEventYAML":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateEventYAML(p0, p1, p2)
	case "UpdateHPAYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateHPAYaml(p0, p1, p2)
	case "UpdateHelmRepository":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateHelmRepository(p0)
	case "UpdateIngressClassYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateIngressClassYaml(p0, p1)
	case "UpdateIngressYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateIngressYaml(p0, p1, p2)
	case "UpdateJobYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateJobYaml(p0, p1, p2)
	case "UpdateLeaseYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateLeaseYaml(p0, p1, p2)
	case "UpdateLimitRangeYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateLimitRangeYaml(p0, p1, p2)
	case "UpdateMutatingWebhookConfigurationYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateMutatingWebhookConfigurationYaml(p0, p1)
	case "UpdateNamespaceYAML":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateNamespaceYAML(p0, p1)
	case "UpdateNetworkPolicyYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateNetworkPolicyYaml(p0, p1, p2)
	case "UpdateNodeYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateNodeYaml(p0, p1)
	case "UpdatePDBYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdatePDBYaml(p0, p1, p2)
	case "UpdatePVCYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdatePVCYaml(p0, p1, p2)
	case "UpdatePVYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdatePVYaml(p0, p1)
	case "UpdatePodYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdatePodYaml(p0, p1, p2)
	case "UpdatePortForwardConfig":
		p0, err := unmarshalArg[PortForwardConfig](args, 0)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdatePortForwardConfig(p0)
	case "UpdatePriorityClassYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdatePriorityClassYaml(p0, p1)
	case "UpdateReplicaSetYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateReplicaSetYaml(p0, p1, p2)
	case "UpdateResourceQuotaYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateResourceQuotaYaml(p0, p1, p2)
	case "UpdateRoleBindingYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateRoleBindingYaml(p0, p1, p2)
	case "UpdateRoleYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateRoleYaml(p0, p1, p2)
	case "UpdateSecretData":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[map[string]string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateSecretData(p0, p1, p2)
	case "UpdateSecretYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateSecretYaml(p0, p1, p2)
	case "UpdateServiceAccountYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateServiceAccountYaml(p0, p1, p2)
	case "UpdateServiceYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateServiceYaml(p0, p1, p2)
	case "UpdateStatefulSetYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateStatefulSetYaml(p0, p1, p2)
	case "UpdateStorageClassYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateStorageClassYaml(p0, p1)
	case "UpdateValidatingWebhookConfigurationYaml":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpdateValidatingWebhookConfigurationYaml(p0, p1)
	case "UpgradeHelmRelease":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[helm.UpgradeOptions](args, 2)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UpgradeHelmRelease(p0, p1, p2)
	case "UploadFileToPod":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		p4, err := unmarshalArg[string](args, 4)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UploadFileToPod(p0, p1, p2, p3, p4)
	case "UploadToPod":
		p0, err := unmarshalArg[string](args, 0)
		if err != nil {
			return nil, err
		}
		p1, err := unmarshalArg[string](args, 1)
		if err != nil {
			return nil, err
		}
		p2, err := unmarshalArg[string](args, 2)
		if err != nil {
			return nil, err
		}
		p3, err := unmarshalArg[string](args, 3)
		if err != nil {
			return nil, err
		}
		return nil, c.app.UploadToPod(p0, p1, p2, p3)
	default:
		return nil, fmt.Errorf("method %q not found", methodName)
	}
}
