import { describe, it, expect } from 'vitest';

// Import all delete/restart bindings to verify their signatures.
// These are auto-generated by Wails from Go function signatures in app.go.
// If a Go function signature changes, the binding arity changes, and these
// tests will catch mismatches before they cause silent runtime bugs.
//
// Bug context: useBulkActions previously passed (context, namespace, name) but
// most Go Delete functions only accepted (namespace, name). The context string
// was silently treated as namespace, causing deletes to target the wrong resource.
import {
    // Namespaced delete functions — must take exactly 2 args: (namespace, name)
    DeletePod,
    ForceDeletePod,
    DeleteDeployment,
    DeleteStatefulSet,
    DeleteDaemonSet,
    DeleteService,
    DeleteConfigMap,
    DeleteSecret,
    DeleteCronJob,
    DeleteJob,
    DeleteReplicaSet,
    DeleteIngress,
    DeleteHPA,
    DeletePDB,
    DeletePVC,
    DeleteRole,
    DeleteRoleBinding,
    DeleteServiceAccount,
    DeleteNetworkPolicy,
    DeleteResourceQuota,
    DeleteLimitRange,
    DeleteEndpoints,
    DeleteEndpointSlice,
    DeleteLease,
    DeleteEvent,
    // Cluster-scoped delete functions — must take exactly 1 arg: (name)
    DeleteNamespace,
    DeleteNode,
    DeletePV,
    DeleteStorageClass,
    DeleteClusterRole,
    DeleteClusterRoleBinding,
    DeleteCRD,
    DeleteCSIDriver,
    DeleteCSINode,
    DeleteIngressClass,
    DeletePriorityClass,
    DeleteMutatingWebhookConfiguration,
    DeleteValidatingWebhookConfiguration,
    // Restart functions — must take exactly 2 args: (namespace, name)
    RestartDeployment,
    RestartStatefulSet,
    RestartDaemonSet,
} from '../../wailsjs/go/main/App';

describe('Wails binding signatures for delete/restart operations', () => {
    describe('namespaced delete functions take exactly 2 args (namespace, name)', () => {
        const namespacedDeleteFns = [
            ['DeletePod', DeletePod],
            ['ForceDeletePod', ForceDeletePod],
            ['DeleteDeployment', DeleteDeployment],
            ['DeleteStatefulSet', DeleteStatefulSet],
            ['DeleteDaemonSet', DeleteDaemonSet],
            ['DeleteService', DeleteService],
            ['DeleteConfigMap', DeleteConfigMap],
            ['DeleteSecret', DeleteSecret],
            ['DeleteCronJob', DeleteCronJob],
            ['DeleteJob', DeleteJob],
            ['DeleteReplicaSet', DeleteReplicaSet],
            ['DeleteIngress', DeleteIngress],
            ['DeleteHPA', DeleteHPA],
            ['DeletePDB', DeletePDB],
            ['DeletePVC', DeletePVC],
            ['DeleteRole', DeleteRole],
            ['DeleteRoleBinding', DeleteRoleBinding],
            ['DeleteServiceAccount', DeleteServiceAccount],
            ['DeleteNetworkPolicy', DeleteNetworkPolicy],
            ['DeleteResourceQuota', DeleteResourceQuota],
            ['DeleteLimitRange', DeleteLimitRange],
            ['DeleteEndpoints', DeleteEndpoints],
            ['DeleteEndpointSlice', DeleteEndpointSlice],
            ['DeleteLease', DeleteLease],
            ['DeleteEvent', DeleteEvent],
        ];

        namespacedDeleteFns.forEach(([name, fn]) => {
            it(`${name} takes 2 args`, () => {
                expect(fn.length).toBe(2);
            });
        });
    });

    describe('cluster-scoped delete functions take exactly 1 arg (name)', () => {
        const clusterScopedDeleteFns = [
            ['DeleteNamespace', DeleteNamespace],
            ['DeleteNode', DeleteNode],
            ['DeletePV', DeletePV],
            ['DeleteStorageClass', DeleteStorageClass],
            ['DeleteClusterRole', DeleteClusterRole],
            ['DeleteClusterRoleBinding', DeleteClusterRoleBinding],
            ['DeleteCRD', DeleteCRD],
            ['DeleteCSIDriver', DeleteCSIDriver],
            ['DeleteCSINode', DeleteCSINode],
            ['DeleteIngressClass', DeleteIngressClass],
            ['DeletePriorityClass', DeletePriorityClass],
            ['DeleteMutatingWebhookConfiguration', DeleteMutatingWebhookConfiguration],
            ['DeleteValidatingWebhookConfiguration', DeleteValidatingWebhookConfiguration],
        ];

        clusterScopedDeleteFns.forEach(([name, fn]) => {
            it(`${name} takes 1 arg`, () => {
                expect(fn.length).toBe(1);
            });
        });
    });

    describe('restart functions take exactly 2 args (namespace, name)', () => {
        const restartFns = [
            ['RestartDeployment', RestartDeployment],
            ['RestartStatefulSet', RestartStatefulSet],
            ['RestartDaemonSet', RestartDaemonSet],
        ];

        restartFns.forEach(([name, fn]) => {
            it(`${name} takes 2 args`, () => {
                expect(fn.length).toBe(2);
            });
        });
    });
});
