// Context providers and hooks - barrel export
export { K8sProvider, useK8s } from './K8sContext'
export { UIProvider, useUI } from './UIContext'
export { MenuProvider, useMenu } from './MenuContext'
export { DebugProvider, useDebug, useDebugLog, DEBUG_SOURCE, DEBUG_CATEGORIES, CATEGORY_COLORS } from './DebugContext'
export type { DebugSource, DebugCategory, DebugLogEntry } from './DebugContext'
export { ConfigProvider, useConfig } from './ConfigContext'
export { NotificationProvider, useNotification } from './NotificationContext'
export { ThemeProvider, useTheme, UI_FONTS, MONO_FONTS } from './ThemeContext'
export { AIChatProvider, useAIChat } from './AIChatContext'
export { IssueDetectorProvider, useIssueDetector } from './IssueDetectorContext'
