apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubikles-accelerator.fullname" . }}-verifier
  labels:
    {{- include "kubikles-accelerator.labels" . | nindent 4 }}
type: Opaque
immutable: true
data:
  creatorVerifier: {{ .Values.auth.creatorVerifier | b64enc | quote }}
