apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubikles-accelerator.fullname" . }}
  labels:
    {{- include "kubikles-accelerator.labels" . | nindent 4 }}
automountServiceAccountToken: false
