// @ts-nocheck
// Wails API Adapter - automatically routes to Wails bindings or HTTP based on runtime mode
//
// SYNC: This adapter mirrors wailsjs/go/main/App.js (auto-generated by Wails)
// Source: frontend/wailsjs/go/main/App.js (Wails-generated)
// Backend: app.go - App struct methods
//
// MAINTENANCE:
// When adding new methods to the Go App struct:
// 1. Wails regenerates wailsjs/go/main/App.js automatically (wails dev/build)
// 2. Copy the new export to this file with the proxy pattern:
//    export function NewMethod(...args) { return AppProxy.NewMethod(...args); }
//
// To verify sync, run:
//   diff <(grep "^export function" frontend/wailsjs/go/main/App.js | sort) \
//        <(grep "^export function" frontend/src/lib/wailsjs-adapter/go/main/App.js | sort)

const isServerMode = () => typeof window.go === 'undefined';

// HTTP API caller for server mode
const API_TIMEOUT_MS = 60_000; // 60 seconds

async function callAPI(method, ...args) {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), API_TIMEOUT_MS);

    try {
        const response = await fetch('/api/call', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ method, args }),
            signal: controller.signal,
        });

        if (!response.ok) {
            const error = await response.text();
            throw new Error(error || `API call failed: ${method}`);
        }

        const result = await response.json();
        if (result.error) {
            throw new Error(result.error);
        }
        return result.data;
    } catch (err) {
        if (err.name === 'AbortError') {
            throw new Error(`API call timed out: ${method}`);
        }
        throw err;
    } finally {
        clearTimeout(timeoutId);
    }
}

// Create a Proxy that intercepts all property access and returns appropriate functions
// This eliminates the need to manually export every function
const handler = {
    get(target, prop) {
        // Return a function that routes based on mode
        return async function(...args) {
            if (isServerMode()) {
                return callAPI(prop, ...args);
            } else {
                // Use Wails bindings
                if (window.go?.main?.App?.[prop]) {
                    return window.go.main.App[prop](...args);
                }
                throw new Error(`Function ${prop} not found in Wails bindings`);
            }
        };
    }
};

const AppProxy = new Proxy({}, handler);

// Export each function individually for tree-shaking compatibility
// The Proxy handles the actual implementation, but we need named exports
// to match what components import

// Generate exports dynamically at module load time
// In Wails mode, we can introspect window.go.main.App
// In server mode or at build time, we export everything through the proxy

export function AddHelmRepository(...args) { return AppProxy.AddHelmRepository(...args); }
export function AddPortForwardConfig(...args) { return AppProxy.AddPortForwardConfig(...args); }
export function ApplyYAML(...args) { return AppProxy.ApplyYAML(...args); }
export function CancelConnectionTest(...args) { return AppProxy.CancelConnectionTest(...args); }
export function CancelAIRequest(...args) { return AppProxy.CancelAIRequest(...args); }
export function CancelListRequest(...args) { return AppProxy.CancelListRequest(...args); }
export function CancelMetricsRequest(...args) { return AppProxy.CancelMetricsRequest(...args); }
export function CheckAIProvider(...args) { return AppProxy.CheckAIProvider(...args); }
export function CheckRBACAccess(...args) { return AppProxy.CheckRBACAccess(...args); }
export function ClearAISession(...args) { return AppProxy.ClearAISession(...args); }
export function ClearAnthropicAPIKey(...args) { return AppProxy.ClearAnthropicAPIKey(...args); }
export function ClearPrometheusConfig(...args) { return AppProxy.ClearPrometheusConfig(...args); }
export function CloseAISession(...args) { return AppProxy.CloseAISession(...args); }
export function CloseTerminalSession(...args) { return AppProxy.CloseTerminalSession(...args); }
export function CollectIngressHostnames(...args) { return AppProxy.CollectIngressHostnames(...args); }
export function ConfirmDialog(...args) { return AppProxy.ConfirmDialog(...args); }
export function CreateNodeDebugPod(...args) { return AppProxy.CreateNodeDebugPod(...args); }
export function CreatePodDirectory(...args) { return AppProxy.CreatePodDirectory(...args); }
export function DeleteContext(...args) { return AppProxy.DeleteContext(...args); }
export function DeleteCRD(...args) { return AppProxy.DeleteCRD(...args); }
export function DeleteCSIDriver(...args) { return AppProxy.DeleteCSIDriver(...args); }
export function DeleteCSINode(...args) { return AppProxy.DeleteCSINode(...args); }
export function DeleteClusterRole(...args) { return AppProxy.DeleteClusterRole(...args); }
export function DeleteClusterRoleBinding(...args) { return AppProxy.DeleteClusterRoleBinding(...args); }
export function DeleteConfigMap(...args) { return AppProxy.DeleteConfigMap(...args); }
export function DeleteCronJob(...args) { return AppProxy.DeleteCronJob(...args); }
export function DeleteCustomResource(...args) { return AppProxy.DeleteCustomResource(...args); }
export function DeleteDaemonSet(...args) { return AppProxy.DeleteDaemonSet(...args); }
export function DeleteDeployment(...args) { return AppProxy.DeleteDeployment(...args); }
export function DeleteEndpointSlice(...args) { return AppProxy.DeleteEndpointSlice(...args); }
export function DeleteEndpoints(...args) { return AppProxy.DeleteEndpoints(...args); }
export function DeleteEvent(...args) { return AppProxy.DeleteEvent(...args); }
export function DeleteHPA(...args) { return AppProxy.DeleteHPA(...args); }
export function DeleteIngress(...args) { return AppProxy.DeleteIngress(...args); }
export function DeleteIngressClass(...args) { return AppProxy.DeleteIngressClass(...args); }
export function DeleteJob(...args) { return AppProxy.DeleteJob(...args); }
export function DeleteLease(...args) { return AppProxy.DeleteLease(...args); }
export function DeleteLimitRange(...args) { return AppProxy.DeleteLimitRange(...args); }
export function DeleteMutatingWebhookConfiguration(...args) { return AppProxy.DeleteMutatingWebhookConfiguration(...args); }
export function DeleteNamespace(...args) { return AppProxy.DeleteNamespace(...args); }
export function DeleteNetworkPolicy(...args) { return AppProxy.DeleteNetworkPolicy(...args); }
export function DeleteNode(...args) { return AppProxy.DeleteNode(...args); }
export function DeletePDB(...args) { return AppProxy.DeletePDB(...args); }
export function DeletePV(...args) { return AppProxy.DeletePV(...args); }
export function DeletePVC(...args) { return AppProxy.DeletePVC(...args); }
export function DeletePod(...args) { return AppProxy.DeletePod(...args); }
export function DeletePodFile(...args) { return AppProxy.DeletePodFile(...args); }
export function DeletePortForwardConfig(...args) { return AppProxy.DeletePortForwardConfig(...args); }
export function DeletePriorityClass(...args) { return AppProxy.DeletePriorityClass(...args); }
export function DeleteReplicaSet(...args) { return AppProxy.DeleteReplicaSet(...args); }
export function DeleteResourceQuota(...args) { return AppProxy.DeleteResourceQuota(...args); }
export function DeleteRole(...args) { return AppProxy.DeleteRole(...args); }
export function DeleteRoleBinding(...args) { return AppProxy.DeleteRoleBinding(...args); }
export function DeleteSecret(...args) { return AppProxy.DeleteSecret(...args); }
export function DeleteService(...args) { return AppProxy.DeleteService(...args); }
export function DeleteServiceAccount(...args) { return AppProxy.DeleteServiceAccount(...args); }
export function DeleteStatefulSet(...args) { return AppProxy.DeleteStatefulSet(...args); }
export function DeleteStorageClass(...args) { return AppProxy.DeleteStorageClass(...args); }
export function DeleteValidatingWebhookConfiguration(...args) { return AppProxy.DeleteValidatingWebhookConfiguration(...args); }
export function DetectIngressController(...args) { return AppProxy.DetectIngressController(...args); }
export function DetectPrometheus(...args) { return AppProxy.DetectPrometheus(...args); }
export function DiffResources(...args) { return AppProxy.DiffResources(...args); }
export function DownloadPodFile(...args) { return AppProxy.DownloadPodFile(...args); }
export function DownloadPodFiles(...args) { return AppProxy.DownloadPodFiles(...args); }
export function DownloadPodFolder(...args) { return AppProxy.DownloadPodFolder(...args); }
export function EvictPod(...args) { return AppProxy.EvictPod(...args); }
export function ExpandDependencyNode(...args) { return AppProxy.ExpandDependencyNode(...args); }
export function ForceDeletePod(...args) { return AppProxy.ForceDeletePod(...args); }
export function ForceHelmReleaseStatus(...args) { return AppProxy.ForceHelmReleaseStatus(...args); }
export function GetAIModels(...args) { return AppProxy.GetAIModels(...args); }
export function GetAIProviders(...args) { return AppProxy.GetAIProviders(...args); }
export function GetAnthropicAPIKeyStatus(...args) { return AppProxy.GetAnthropicAPIKeyStatus(...args); }
export function GetActivePortForwards(...args) { return AppProxy.GetActivePortForwards(...args); }
export function GetAllCertificateInfo(...args) { return AppProxy.GetAllCertificateInfo(...args); }
export function GetAllContainersLogs(...args) { return AppProxy.GetAllContainersLogs(...args); }
export function GetAllContainersLogsAfter(...args) { return AppProxy.GetAllContainersLogsAfter(...args); }
export function GetAllContainersLogsAll(...args) { return AppProxy.GetAllContainersLogsAll(...args); }
export function GetAllContainersLogsBefore(...args) { return AppProxy.GetAllContainersLogsBefore(...args); }
export function GetAllContainersLogsFromStart(...args) { return AppProxy.GetAllContainersLogsFromStart(...args); }
export function GetAllPodLogs(...args) { return AppProxy.GetAllPodLogs(...args); }
export function GetAllPodsLogs(...args) { return AppProxy.GetAllPodsLogs(...args); }
export function GetAllPodsLogsAfter(...args) { return AppProxy.GetAllPodsLogsAfter(...args); }
export function GetAllPodsLogsAll(...args) { return AppProxy.GetAllPodsLogsAll(...args); }
export function GetAllPodsLogsBefore(...args) { return AppProxy.GetAllPodsLogsBefore(...args); }
export function GetAllPodsLogsFromStart(...args) { return AppProxy.GetAllPodsLogsFromStart(...args); }
export function GetAvailablePort(...args) { return AppProxy.GetAvailablePort(...args); }
export function GetCRDPrinterColumns(...args) { return AppProxy.GetCRDPrinterColumns(...args); }
export function GetCRDYaml(...args) { return AppProxy.GetCRDYaml(...args); }
export function GetCSIDriverYaml(...args) { return AppProxy.GetCSIDriverYaml(...args); }
export function GetCSINodeYaml(...args) { return AppProxy.GetCSINodeYaml(...args); }
export function GetCachedPrometheusConfig(...args) { return AppProxy.GetCachedPrometheusConfig(...args); }
export function GetCertificateInfo(...args) { return AppProxy.GetCertificateInfo(...args); }
export function GetClusterRoleBindingYaml(...args) { return AppProxy.GetClusterRoleBindingYaml(...args); }
export function GetClusterRoleYaml(...args) { return AppProxy.GetClusterRoleYaml(...args); }
export function GetConfigMapData(...args) { return AppProxy.GetConfigMapData(...args); }
export function GetConfigMapYaml(...args) { return AppProxy.GetConfigMapYaml(...args); }
export function GetContextDetails(...args) { return AppProxy.GetContextDetails(...args); }
export function GetControllerMetricsHistory(...args) { return AppProxy.GetControllerMetricsHistory(...args); }
export function GetControllerMetricsHistoryRange(...args) { return AppProxy.GetControllerMetricsHistoryRange(...args); }
export function GetCrashLogPath(...args) { return AppProxy.GetCrashLogPath(...args); }
export function GetCronJobYaml(...args) { return AppProxy.GetCronJobYaml(...args); }
export function GetCurrentContext(...args) { return AppProxy.GetCurrentContext(...args); }
export function GetCurrentTheme(...args) { return AppProxy.GetCurrentTheme(...args); }
export function GetCustomResourceEvents(...args) { return AppProxy.GetCustomResourceEvents(...args); }
export function GetCustomResourceYaml(...args) { return AppProxy.GetCustomResourceYaml(...args); }
export function GetDaemonSetYaml(...args) { return AppProxy.GetDaemonSetYaml(...args); }
export function GetDebugClusterConfig(...args) { return AppProxy.GetDebugClusterConfig(...args); }
export function GetDeploymentYaml(...args) { return AppProxy.GetDeploymentYaml(...args); }
export function GetEndpointSliceYaml(...args) { return AppProxy.GetEndpointSliceYaml(...args); }
export function GetEndpointsYaml(...args) { return AppProxy.GetEndpointsYaml(...args); }
export function GetEventYAML(...args) { return AppProxy.GetEventYAML(...args); }
export function GetFlowTimeline(...args) { return AppProxy.GetFlowTimeline(...args); }
export function GetHPAYaml(...args) { return AppProxy.GetHPAYaml(...args); }
export function GetHelmChartVersions(...args) { return AppProxy.GetHelmChartVersions(...args); }
export function GetHelmRelease(...args) { return AppProxy.GetHelmRelease(...args); }
export function GetHelmReleaseAllValues(...args) { return AppProxy.GetHelmReleaseAllValues(...args); }
export function GetHelmReleaseHistory(...args) { return AppProxy.GetHelmReleaseHistory(...args); }
export function GetHelmReleaseResources(...args) { return AppProxy.GetHelmReleaseResources(...args); }
export function GetHelmReleaseValues(...args) { return AppProxy.GetHelmReleaseValues(...args); }
export function GetIngressClassYaml(...args) { return AppProxy.GetIngressClassYaml(...args); }
export function GetIngressForwardState(...args) { return AppProxy.GetIngressForwardState(...args); }
export function GetIngressYaml(...args) { return AppProxy.GetIngressYaml(...args); }
export function GetIssueRulesDir(...args) { return AppProxy.GetIssueRulesDir(...args); }
export function GetJobYaml(...args) { return AppProxy.GetJobYaml(...args); }
export function GetK8sInitError(...args) { return AppProxy.GetK8sInitError(...args); }
export function GetLeaseYaml(...args) { return AppProxy.GetLeaseYaml(...args); }
export function GetLimitRangeYaml(...args) { return AppProxy.GetLimitRangeYaml(...args); }
export function GetListRequestStats(...args) { return AppProxy.GetListRequestStats(...args); }
export function GetManagedHosts(...args) { return AppProxy.GetManagedHosts(...args); }
export function GetMetricsEventMarkers(...args) { return AppProxy.GetMetricsEventMarkers(...args); }
export function GetMetricsRequestStats(...args) { return AppProxy.GetMetricsRequestStats(...args); }
export function GetMutatingWebhookConfigurationYaml(...args) { return AppProxy.GetMutatingWebhookConfigurationYaml(...args); }
export function GetMultiPodLogs(...args) { return AppProxy.GetMultiPodLogs(...args); }
export function GetNamespaceMetricsHistory(...args) { return AppProxy.GetNamespaceMetricsHistory(...args); }
export function GetNamespaceMetricsHistoryRange(...args) { return AppProxy.GetNamespaceMetricsHistoryRange(...args); }
export function GetNamespaceResourceCounts(...args) { return AppProxy.GetNamespaceResourceCounts(...args); }
export function GetNamespaceYAML(...args) { return AppProxy.GetNamespaceYAML(...args); }
export function GetNetworkPolicyYaml(...args) { return AppProxy.GetNetworkPolicyYaml(...args); }
export function GetNodeMetrics(...args) { return AppProxy.GetNodeMetrics(...args); }
export function GetNodeMetricsFromPrometheus(...args) { return AppProxy.GetNodeMetricsFromPrometheus(...args); }
export function GetNodeMetricsHistory(...args) { return AppProxy.GetNodeMetricsHistory(...args); }
export function GetNodeMetricsHistoryRange(...args) { return AppProxy.GetNodeMetricsHistoryRange(...args); }
export function GetNodeYaml(...args) { return AppProxy.GetNodeYaml(...args); }
export function GetPDBYaml(...args) { return AppProxy.GetPDBYaml(...args); }
export function GetPVCYaml(...args) { return AppProxy.GetPVCYaml(...args); }
export function GetPVYaml(...args) { return AppProxy.GetPVYaml(...args); }
export function GetPerformanceMetrics(...args) { return AppProxy.GetPerformanceMetrics(...args); }
export function GetPodEvictionInfo(...args) { return AppProxy.GetPodEvictionInfo(...args); }
export function GetPodLogs(...args) { return AppProxy.GetPodLogs(...args); }
export function GetPodLogsAfter(...args) { return AppProxy.GetPodLogsAfter(...args); }
export function GetPodLogsBefore(...args) { return AppProxy.GetPodLogsBefore(...args); }
export function GetPodLogsFromStart(...args) { return AppProxy.GetPodLogsFromStart(...args); }
export function GetPodMetrics(...args) { return AppProxy.GetPodMetrics(...args); }
export function GetPodMetricsFromPrometheus(...args) { return AppProxy.GetPodMetricsFromPrometheus(...args); }
export function GetPodMetricsHistory(...args) { return AppProxy.GetPodMetricsHistory(...args); }
export function GetPodMetricsHistoryRange(...args) { return AppProxy.GetPodMetricsHistoryRange(...args); }
export function GetPodPorts(...args) { return AppProxy.GetPodPorts(...args); }
export function GetPodYaml(...args) { return AppProxy.GetPodYaml(...args); }
export function GetPortForwardConfigs(...args) { return AppProxy.GetPortForwardConfigs(...args); }
export function GetPriorityClassYaml(...args) { return AppProxy.GetPriorityClassYaml(...args); }
export function GetRandomAvailablePort(...args) { return AppProxy.GetRandomAvailablePort(...args); }
export function GetReplicaSetYaml(...args) { return AppProxy.GetReplicaSetYaml(...args); }
export function GetResourceDependencies(...args) { return AppProxy.GetResourceDependencies(...args); }
export function GetResourceQuotaYaml(...args) { return AppProxy.GetResourceQuotaYaml(...args); }
export function GetRoleBindingYaml(...args) { return AppProxy.GetRoleBindingYaml(...args); }
export function GetRoleYaml(...args) { return AppProxy.GetRoleYaml(...args); }
export function GetSecretData(...args) { return AppProxy.GetSecretData(...args); }
export function GetSecretYaml(...args) { return AppProxy.GetSecretYaml(...args); }
export function GetServiceAccountYaml(...args) { return AppProxy.GetServiceAccountYaml(...args); }
export function GetServicePorts(...args) { return AppProxy.GetServicePorts(...args); }
export function GetServiceYaml(...args) { return AppProxy.GetServiceYaml(...args); }
export function GetStatefulSetYaml(...args) { return AppProxy.GetStatefulSetYaml(...args); }
export function GetStorageClass(...args) { return AppProxy.GetStorageClass(...args); }
export function GetStorageClassYaml(...args) { return AppProxy.GetStorageClassYaml(...args); }
export function GetThemes(...args) { return AppProxy.GetThemes(...args); }
export function GetThemesDir(...args) { return AppProxy.GetThemesDir(...args); }
export function GetToolDiscovery(...args) { return AppProxy.GetToolDiscovery(...args); }
export function GetValidatingWebhookConfigurationYaml(...args) { return AppProxy.GetValidatingWebhookConfigurationYaml(...args); }
export function GetVersionInfo(...args) { return AppProxy.GetVersionInfo(...args); }
export function HelmDryRunUpgrade(...args) { return AppProxy.HelmDryRunUpgrade(...args); }
export function HelmTemplateRelease(...args) { return AppProxy.HelmTemplateRelease(...args); }
export function HelmValidateValues(...args) { return AppProxy.HelmValidateValues(...args); }
export function IsDebugClusterEnabled(...args) { return AppProxy.IsDebugClusterEnabled(...args); }
export function IsHelmAvailable(...args) { return AppProxy.IsHelmAvailable(...args); }
export function IsRequestCancellationEnabled(...args) { return AppProxy.IsRequestCancellationEnabled(...args); }
export function ListCRDs(...args) { return AppProxy.ListCRDs(...args); }
export function ListCSIDrivers(...args) { return AppProxy.ListCSIDrivers(...args); }
export function ListCSINodes(...args) { return AppProxy.ListCSINodes(...args); }
export function ListChartSources(...args) { return AppProxy.ListChartSources(...args); }
export function ListClusterRoleBindings(...args) { return AppProxy.ListClusterRoleBindings(...args); }
export function ListClusterRoles(...args) { return AppProxy.ListClusterRoles(...args); }
export function ListConfigMaps(...args) { return AppProxy.ListConfigMaps(...args); }
export function ListContexts(...args) { return AppProxy.ListContexts(...args); }
export function ListCronJobs(...args) { return AppProxy.ListCronJobs(...args); }
export function ListCustomResources(...args) { return AppProxy.ListCustomResources(...args); }
export function ListDaemonSets(...args) { return AppProxy.ListDaemonSets(...args); }
export function ListDeployments(...args) { return AppProxy.ListDeployments(...args); }
export function ListEndpointSlices(...args) { return AppProxy.ListEndpointSlices(...args); }
export function ListEndpoints(...args) { return AppProxy.ListEndpoints(...args); }
export function ListEvents(...args) { return AppProxy.ListEvents(...args); }
export function ListHPAs(...args) { return AppProxy.ListHPAs(...args); }
export function ListHelmReleases(...args) { return AppProxy.ListHelmReleases(...args); }
export function ListHelmRepositories(...args) { return AppProxy.ListHelmRepositories(...args); }
export function ListIngressClasses(...args) { return AppProxy.ListIngressClasses(...args); }
export function ListIngresses(...args) { return AppProxy.ListIngresses(...args); }
export function ListIssueRules(...args) { return AppProxy.ListIssueRules(...args); }
export function ListJobs(...args) { return AppProxy.ListJobs(...args); }
export function ListLeases(...args) { return AppProxy.ListLeases(...args); }
export function ListLimitRanges(...args) { return AppProxy.ListLimitRanges(...args); }
export function ListMutatingWebhookConfigurations(...args) { return AppProxy.ListMutatingWebhookConfigurations(...args); }
export function ListNamespaces(...args) { return AppProxy.ListNamespaces(...args); }
export function ListNamespacesForContext(...args) { return AppProxy.ListNamespacesForContext(...args); }
export function ListNetworkPolicies(...args) { return AppProxy.ListNetworkPolicies(...args); }
export function ListPodsForContext(...args) { return AppProxy.ListPodsForContext(...args); }
export function ListDeploymentsForContext(...args) { return AppProxy.ListDeploymentsForContext(...args); }
export function ListResourceNamesForContext(...args) { return AppProxy.ListResourceNamesForContext(...args); }
export function ListNodes(...args) { return AppProxy.ListNodes(...args); }
export function ListOCIRegistries(...args) { return AppProxy.ListOCIRegistries(...args); }
export function ListPDBs(...args) { return AppProxy.ListPDBs(...args); }
export function ListPVCs(...args) { return AppProxy.ListPVCs(...args); }
export function ListPVs(...args) { return AppProxy.ListPVs(...args); }
export function ListPodFiles(...args) { return AppProxy.ListPodFiles(...args); }
export function ListPods(...args) { return AppProxy.ListPods(...args); }
export function ListPodsForNode(...args) { return AppProxy.ListPodsForNode(...args); }
export function ListPriorityClasses(...args) { return AppProxy.ListPriorityClasses(...args); }
export function ListPrometheusInstalls(...args) { return AppProxy.ListPrometheusInstalls(...args); }
export function ListReplicaSets(...args) { return AppProxy.ListReplicaSets(...args); }
export function ListResourceQuotas(...args) { return AppProxy.ListResourceQuotas(...args); }
export function ListRoleBindings(...args) { return AppProxy.ListRoleBindings(...args); }
export function ListRoles(...args) { return AppProxy.ListRoles(...args); }
export function ListSecrets(...args) { return AppProxy.ListSecrets(...args); }
export function ListSecretsMetadata(...args) { return AppProxy.ListSecretsMetadata(...args); }
export function ListServiceAccounts(...args) { return AppProxy.ListServiceAccounts(...args); }
export function ListServices(...args) { return AppProxy.ListServices(...args); }
export function ListStatefulSets(...args) { return AppProxy.ListStatefulSets(...args); }
export function ListStorageClasses(...args) { return AppProxy.ListStorageClasses(...args); }
export function ListValidatingWebhookConfigurations(...args) { return AppProxy.ListValidatingWebhookConfigurations(...args); }
export function LogDebug(...args) { return AppProxy.LogDebug(...args); }
export function LogMessage(...args) { return AppProxy.LogMessage(...args); }
export function LoginACRWithAzureCLI(...args) { return AppProxy.LoginACRWithAzureCLI(...args); }
export function LoginOCIRegistry(...args) { return AppProxy.LoginOCIRegistry(...args); }
export function LogoutOCIRegistry(...args) { return AppProxy.LogoutOCIRegistry(...args); }
export function OpenCrashLogDir(...args) { return AppProxy.OpenCrashLogDir(...args); }
export function OpenIssueRulesDir(...args) { return AppProxy.OpenIssueRulesDir(...args); }
export function OpenThemesDir(...args) { return AppProxy.OpenThemesDir(...args); }
export function RefreshIngressHostnames(...args) { return AppProxy.RefreshIngressHostnames(...args); }
export function ReloadIssueRules(...args) { return AppProxy.ReloadIssueRules(...args); }
export function ReloadThemes(...args) { return AppProxy.ReloadThemes(...args); }
export function RenameContext(...args) { return AppProxy.RenameContext(...args); }
export function RemoveHelmRepository(...args) { return AppProxy.RemoveHelmRepository(...args); }
export function RemoveOCIRegistry(...args) { return AppProxy.RemoveOCIRegistry(...args); }
export function ResetDebugCluster(...args) { return AppProxy.ResetDebugCluster(...args); }
export function ResolveTopLevelOwner(...args) { return AppProxy.ResolveTopLevelOwner(...args); }
export function ResizePVC(...args) { return AppProxy.ResizePVC(...args); }
export function ResizeTerminal(...args) { return AppProxy.ResizeTerminal(...args); }
export function RestartDaemonSet(...args) { return AppProxy.RestartDaemonSet(...args); }
export function RestartDeployment(...args) { return AppProxy.RestartDeployment(...args); }
export function RestartStatefulSet(...args) { return AppProxy.RestartStatefulSet(...args); }
export function RollbackHelmRelease(...args) { return AppProxy.RollbackHelmRelease(...args); }
export function RunIssueScan(...args) { return AppProxy.RunIssueScan(...args); }
export function SaveDebugLogs(...args) { return AppProxy.SaveDebugLogs(...args); }
export function SaveLogFile(...args) { return AppProxy.SaveLogFile(...args); }
export function SaveLogsBundle(...args) { return AppProxy.SaveLogsBundle(...args); }
export function SavePodLogs(...args) { return AppProxy.SavePodLogs(...args); }
export function SavePrometheusConfig(...args) { return AppProxy.SavePrometheusConfig(...args); }
export function SaveYamlBackup(...args) { return AppProxy.SaveYamlBackup(...args); }
export function ScaleDeployment(...args) { return AppProxy.ScaleDeployment(...args); }
export function ScaleReplicaSet(...args) { return AppProxy.ScaleReplicaSet(...args); }
export function ScaleStatefulSet(...args) { return AppProxy.ScaleStatefulSet(...args); }
export function SearchChartInSource(...args) { return AppProxy.SearchChartInSource(...args); }
export function SearchHelmChart(...args) { return AppProxy.SearchHelmChart(...args); }
export function SelectKubeconfigFile(...args) { return AppProxy.SelectKubeconfigFile(...args); }
export function SendAIMessage(...args) { return AppProxy.SendAIMessage(...args); }
export function SendTerminalInput(...args) { return AppProxy.SendTerminalInput(...args); }
export function SetAnthropicAPIKey(...args) { return AppProxy.SetAnthropicAPIKey(...args); }
export function SetClientPoolSize(...args) { return AppProxy.SetClientPoolSize(...args); }
export function SetDebugClusterConfig(...args) { return AppProxy.SetDebugClusterConfig(...args); }
export function SetDebugEnabled(...args) { return AppProxy.SetDebugEnabled(...args); }
export function SetEventCoalescerFrameInterval(...args) { return AppProxy.SetEventCoalescerFrameInterval(...args); }
export function SetEmitter(...args) { return AppProxy.SetEmitter(...args); }
export function SetExtraKubeconfigPaths(...args) { return AppProxy.SetExtraKubeconfigPaths(...args); }
export function SetForceHTTP1(...args) { return AppProxy.SetForceHTTP1(...args); }
export function SetHelmRepositoryPriority(...args) { return AppProxy.SetHelmRepositoryPriority(...args); }
export function SetK8sAPITimeout(...args) { return AppProxy.SetK8sAPITimeout(...args); }
export function SetNodeSchedulable(...args) { return AppProxy.SetNodeSchedulable(...args); }
export function SetOCIRegistryPriority(...args) { return AppProxy.SetOCIRegistryPriority(...args); }
export function SetRequestCancellationEnabled(...args) { return AppProxy.SetRequestCancellationEnabled(...args); }
export function SetTheme(...args) { return AppProxy.SetTheme(...args); }
export function StartAISession(...args) { return AppProxy.StartAISession(...args); }
export function StartAllContainersLogStream(...args) { return AppProxy.StartAllContainersLogStream(...args); }
export function StartAllPodsLogStream(...args) { return AppProxy.StartAllPodsLogStream(...args); }
export function StartAutoStartPortForwards(...args) { return AppProxy.StartAutoStartPortForwards(...args); }
export function StartIngressForward(...args) { return AppProxy.StartIngressForward(...args); }
export function StartLogStream(...args) { return AppProxy.StartLogStream(...args); }
export function StartPortForward(...args) { return AppProxy.StartPortForward(...args); }
export function StartTerminalSession(...args) { return AppProxy.StartTerminalSession(...args); }
export function StopAllPortForwards(...args) { return AppProxy.StopAllPortForwards(...args); }
export function StopAllWatchers(...args) { return AppProxy.StopAllWatchers(...args); }
export function StopIngressForward(...args) { return AppProxy.StopIngressForward(...args); }
export function StopLogStream(...args) { return AppProxy.StopLogStream(...args); }
export function StopPortForward(...args) { return AppProxy.StopPortForward(...args); }
export function SubscribeCRDWatcher(...args) { return AppProxy.SubscribeCRDWatcher(...args); }
export function SubscribeResourceWatcher(...args) { return AppProxy.SubscribeResourceWatcher(...args); }
export function SuspendCronJob(...args) { return AppProxy.SuspendCronJob(...args); }
export function SwitchContext(...args) { return AppProxy.SwitchContext(...args); }
export function TestConnection(...args) { return AppProxy.TestConnection(...args); }
export function TestCrash(...args) { return AppProxy.TestCrash(...args); }
export function TestEmit(...args) { return AppProxy.TestEmit(...args); }
export function TestPrometheusEndpoint(...args) { return AppProxy.TestPrometheusEndpoint(...args); }
export function TriggerCronJob(...args) { return AppProxy.TriggerCronJob(...args); }
export function UninstallHelmRelease(...args) { return AppProxy.UninstallHelmRelease(...args); }
export function UnsubscribeWatcher(...args) { return AppProxy.UnsubscribeWatcher(...args); }
export function UpdateAllHelmRepositories(...args) { return AppProxy.UpdateAllHelmRepositories(...args); }
export function UpdateCRDYaml(...args) { return AppProxy.UpdateCRDYaml(...args); }
export function UpdateCSIDriverYaml(...args) { return AppProxy.UpdateCSIDriverYaml(...args); }
export function UpdateCSINodeYaml(...args) { return AppProxy.UpdateCSINodeYaml(...args); }
export function UpdateClusterRoleBindingYaml(...args) { return AppProxy.UpdateClusterRoleBindingYaml(...args); }
export function UpdateClusterRoleYaml(...args) { return AppProxy.UpdateClusterRoleYaml(...args); }
export function UpdateConfigMapData(...args) { return AppProxy.UpdateConfigMapData(...args); }
export function UpdateConfigMapYaml(...args) { return AppProxy.UpdateConfigMapYaml(...args); }
export function UpdateCronJobYaml(...args) { return AppProxy.UpdateCronJobYaml(...args); }
export function UpdateCustomResourceYaml(...args) { return AppProxy.UpdateCustomResourceYaml(...args); }
export function UpdateDaemonSetYaml(...args) { return AppProxy.UpdateDaemonSetYaml(...args); }
export function UpdateDeploymentYaml(...args) { return AppProxy.UpdateDeploymentYaml(...args); }
export function UpdateEndpointSliceYaml(...args) { return AppProxy.UpdateEndpointSliceYaml(...args); }
export function UpdateEndpointsYaml(...args) { return AppProxy.UpdateEndpointsYaml(...args); }
export function UpdateEventYAML(...args) { return AppProxy.UpdateEventYAML(...args); }
export function UpdateHPAYaml(...args) { return AppProxy.UpdateHPAYaml(...args); }
export function UpdateHelmRepository(...args) { return AppProxy.UpdateHelmRepository(...args); }
export function UpdateIngressClassYaml(...args) { return AppProxy.UpdateIngressClassYaml(...args); }
export function UpdateIngressYaml(...args) { return AppProxy.UpdateIngressYaml(...args); }
export function UpdateJobYaml(...args) { return AppProxy.UpdateJobYaml(...args); }
export function UpdateLeaseYaml(...args) { return AppProxy.UpdateLeaseYaml(...args); }
export function UpdateLimitRangeYaml(...args) { return AppProxy.UpdateLimitRangeYaml(...args); }
export function UpdateMutatingWebhookConfigurationYaml(...args) { return AppProxy.UpdateMutatingWebhookConfigurationYaml(...args); }
export function UpdateNamespaceYAML(...args) { return AppProxy.UpdateNamespaceYAML(...args); }
export function UpdateNetworkPolicyYaml(...args) { return AppProxy.UpdateNetworkPolicyYaml(...args); }
export function UpdateNodeYaml(...args) { return AppProxy.UpdateNodeYaml(...args); }
export function UpdatePDBYaml(...args) { return AppProxy.UpdatePDBYaml(...args); }
export function UpdatePVCYaml(...args) { return AppProxy.UpdatePVCYaml(...args); }
export function UpdatePVYaml(...args) { return AppProxy.UpdatePVYaml(...args); }
export function UpdatePodYaml(...args) { return AppProxy.UpdatePodYaml(...args); }
export function UpdatePortForwardConfig(...args) { return AppProxy.UpdatePortForwardConfig(...args); }
export function UpdatePriorityClassYaml(...args) { return AppProxy.UpdatePriorityClassYaml(...args); }
export function UpdateReplicaSetYaml(...args) { return AppProxy.UpdateReplicaSetYaml(...args); }
export function UpdateResourceQuotaYaml(...args) { return AppProxy.UpdateResourceQuotaYaml(...args); }
export function UpdateRoleBindingYaml(...args) { return AppProxy.UpdateRoleBindingYaml(...args); }
export function UpdateRoleYaml(...args) { return AppProxy.UpdateRoleYaml(...args); }
export function UpdateSecretData(...args) { return AppProxy.UpdateSecretData(...args); }
export function UpdateSecretYaml(...args) { return AppProxy.UpdateSecretYaml(...args); }
export function UpdateServiceAccountYaml(...args) { return AppProxy.UpdateServiceAccountYaml(...args); }
export function UpdateServiceYaml(...args) { return AppProxy.UpdateServiceYaml(...args); }
export function UpdateStatefulSetYaml(...args) { return AppProxy.UpdateStatefulSetYaml(...args); }
export function UpdateStorageClassYaml(...args) { return AppProxy.UpdateStorageClassYaml(...args); }
export function UpdateValidatingWebhookConfigurationYaml(...args) { return AppProxy.UpdateValidatingWebhookConfigurationYaml(...args); }
export function UpgradeHelmRelease(...args) { return AppProxy.UpgradeHelmRelease(...args); }
export function UploadFileToPod(...args) { return AppProxy.UploadFileToPod(...args); }
export function UploadToPod(...args) { return AppProxy.UploadToPod(...args); }

// Also export the proxy itself for dynamic access
export default AppProxy;
