// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNodeDebugPod(arg1) {
  return window['go']['main']['App']['CreateNodeDebugPod'](arg1);
}

export function DeleteCRD(arg1) {
  return window['go']['main']['App']['DeleteCRD'](arg1);
}

export function DeleteConfigMap(arg1, arg2) {
  return window['go']['main']['App']['DeleteConfigMap'](arg1, arg2);
}

export function DeleteCronJob(arg1, arg2) {
  return window['go']['main']['App']['DeleteCronJob'](arg1, arg2);
}

export function DeleteDaemonSet(arg1, arg2) {
  return window['go']['main']['App']['DeleteDaemonSet'](arg1, arg2);
}

export function DeleteDeployment(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteDeployment'](arg1, arg2, arg3);
}

export function DeleteEvent(arg1, arg2) {
  return window['go']['main']['App']['DeleteEvent'](arg1, arg2);
}

export function DeleteJob(arg1, arg2) {
  return window['go']['main']['App']['DeleteJob'](arg1, arg2);
}

export function DeleteNamespace(arg1) {
  return window['go']['main']['App']['DeleteNamespace'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['main']['App']['DeleteNode'](arg1);
}

export function DeletePV(arg1) {
  return window['go']['main']['App']['DeletePV'](arg1);
}

export function DeletePVC(arg1, arg2) {
  return window['go']['main']['App']['DeletePVC'](arg1, arg2);
}

export function DeletePod(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeletePod'](arg1, arg2, arg3);
}

export function DeleteReplicaSet(arg1, arg2) {
  return window['go']['main']['App']['DeleteReplicaSet'](arg1, arg2);
}

export function DeleteSecret(arg1, arg2) {
  return window['go']['main']['App']['DeleteSecret'](arg1, arg2);
}

export function DeleteService(arg1, arg2) {
  return window['go']['main']['App']['DeleteService'](arg1, arg2);
}

export function DeleteStatefulSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteStatefulSet'](arg1, arg2, arg3);
}

export function DeleteStorageClass(arg1) {
  return window['go']['main']['App']['DeleteStorageClass'](arg1);
}

export function ForceDeletePod(arg1, arg2, arg3) {
  return window['go']['main']['App']['ForceDeletePod'](arg1, arg2, arg3);
}

export function GetAllPodLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAllPodLogs'](arg1, arg2, arg3, arg4);
}

export function GetCRDYaml(arg1) {
  return window['go']['main']['App']['GetCRDYaml'](arg1);
}

export function GetConfigMapYaml(arg1, arg2) {
  return window['go']['main']['App']['GetConfigMapYaml'](arg1, arg2);
}

export function GetCronJobYaml(arg1, arg2) {
  return window['go']['main']['App']['GetCronJobYaml'](arg1, arg2);
}

export function GetCurrentContext() {
  return window['go']['main']['App']['GetCurrentContext']();
}

export function GetDaemonSetYaml(arg1, arg2) {
  return window['go']['main']['App']['GetDaemonSetYaml'](arg1, arg2);
}

export function GetDeploymentYaml(arg1, arg2) {
  return window['go']['main']['App']['GetDeploymentYaml'](arg1, arg2);
}

export function GetEventYAML(arg1, arg2) {
  return window['go']['main']['App']['GetEventYAML'](arg1, arg2);
}

export function GetJobYaml(arg1, arg2) {
  return window['go']['main']['App']['GetJobYaml'](arg1, arg2);
}

export function GetNamespaceYAML(arg1) {
  return window['go']['main']['App']['GetNamespaceYAML'](arg1);
}

export function GetNodeYaml(arg1) {
  return window['go']['main']['App']['GetNodeYaml'](arg1);
}

export function GetPVCYaml(arg1, arg2) {
  return window['go']['main']['App']['GetPVCYaml'](arg1, arg2);
}

export function GetPVYaml(arg1) {
  return window['go']['main']['App']['GetPVYaml'](arg1);
}

export function GetPodLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPodLogs'](arg1, arg2, arg3, arg4);
}

export function GetPodYaml(arg1, arg2) {
  return window['go']['main']['App']['GetPodYaml'](arg1, arg2);
}

export function GetReplicaSetYaml(arg1, arg2) {
  return window['go']['main']['App']['GetReplicaSetYaml'](arg1, arg2);
}

export function GetResourceDependencies(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetResourceDependencies'](arg1, arg2, arg3);
}

export function GetSecretData(arg1, arg2) {
  return window['go']['main']['App']['GetSecretData'](arg1, arg2);
}

export function GetSecretYaml(arg1, arg2) {
  return window['go']['main']['App']['GetSecretYaml'](arg1, arg2);
}

export function GetServiceYaml(arg1, arg2) {
  return window['go']['main']['App']['GetServiceYaml'](arg1, arg2);
}

export function GetStatefulSetYaml(arg1, arg2) {
  return window['go']['main']['App']['GetStatefulSetYaml'](arg1, arg2);
}

export function GetStorageClassYaml(arg1) {
  return window['go']['main']['App']['GetStorageClassYaml'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListCRDs() {
  return window['go']['main']['App']['ListCRDs']();
}

export function ListConfigMaps(arg1) {
  return window['go']['main']['App']['ListConfigMaps'](arg1);
}

export function ListContexts() {
  return window['go']['main']['App']['ListContexts']();
}

export function ListCronJobs(arg1) {
  return window['go']['main']['App']['ListCronJobs'](arg1);
}

export function ListDaemonSets(arg1) {
  return window['go']['main']['App']['ListDaemonSets'](arg1);
}

export function ListDeployments(arg1) {
  return window['go']['main']['App']['ListDeployments'](arg1);
}

export function ListEvents(arg1) {
  return window['go']['main']['App']['ListEvents'](arg1);
}

export function ListJobs(arg1) {
  return window['go']['main']['App']['ListJobs'](arg1);
}

export function ListNamespaces() {
  return window['go']['main']['App']['ListNamespaces']();
}

export function ListNodes() {
  return window['go']['main']['App']['ListNodes']();
}

export function ListPVCs(arg1) {
  return window['go']['main']['App']['ListPVCs'](arg1);
}

export function ListPVs() {
  return window['go']['main']['App']['ListPVs']();
}

export function ListPods(arg1) {
  return window['go']['main']['App']['ListPods'](arg1);
}

export function ListReplicaSets(arg1) {
  return window['go']['main']['App']['ListReplicaSets'](arg1);
}

export function ListSecrets(arg1) {
  return window['go']['main']['App']['ListSecrets'](arg1);
}

export function ListServices(arg1) {
  return window['go']['main']['App']['ListServices'](arg1);
}

export function ListStatefulSets(arg1, arg2) {
  return window['go']['main']['App']['ListStatefulSets'](arg1, arg2);
}

export function ListStorageClasses() {
  return window['go']['main']['App']['ListStorageClasses']();
}

export function LogDebug(arg1, arg2) {
  return window['go']['main']['App']['LogDebug'](arg1, arg2);
}

export function OpenTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenTerminal'](arg1, arg2, arg3, arg4);
}

export function OpenTerminalWithCommand(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['OpenTerminalWithCommand'](arg1, arg2, arg3, arg4, arg5);
}

export function RestartDaemonSet(arg1, arg2) {
  return window['go']['main']['App']['RestartDaemonSet'](arg1, arg2);
}

export function RestartDeployment(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestartDeployment'](arg1, arg2, arg3);
}

export function RestartStatefulSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestartStatefulSet'](arg1, arg2, arg3);
}

export function SaveLogFile(arg1) {
  return window['go']['main']['App']['SaveLogFile'](arg1);
}

export function SaveLogsBundle(arg1, arg2) {
  return window['go']['main']['App']['SaveLogsBundle'](arg1, arg2);
}

export function SavePodLogs(arg1, arg2) {
  return window['go']['main']['App']['SavePodLogs'](arg1, arg2);
}

export function SetNodeSchedulable(arg1, arg2) {
  return window['go']['main']['App']['SetNodeSchedulable'](arg1, arg2);
}

export function StartPodWatcher(arg1) {
  return window['go']['main']['App']['StartPodWatcher'](arg1);
}

export function SuspendCronJob(arg1, arg2, arg3) {
  return window['go']['main']['App']['SuspendCronJob'](arg1, arg2, arg3);
}

export function SwitchContext(arg1) {
  return window['go']['main']['App']['SwitchContext'](arg1);
}

export function TestEmit() {
  return window['go']['main']['App']['TestEmit']();
}

export function TriggerCronJob(arg1, arg2) {
  return window['go']['main']['App']['TriggerCronJob'](arg1, arg2);
}

export function UpdateCRDYaml(arg1, arg2) {
  return window['go']['main']['App']['UpdateCRDYaml'](arg1, arg2);
}

export function UpdateConfigMapYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConfigMapYaml'](arg1, arg2, arg3);
}

export function UpdateCronJobYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCronJobYaml'](arg1, arg2, arg3);
}

export function UpdateDaemonSetYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDaemonSetYaml'](arg1, arg2, arg3);
}

export function UpdateDeploymentYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDeploymentYaml'](arg1, arg2, arg3);
}

export function UpdateEventYAML(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateEventYAML'](arg1, arg2, arg3);
}

export function UpdateJobYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateJobYaml'](arg1, arg2, arg3);
}

export function UpdateNamespaceYAML(arg1, arg2) {
  return window['go']['main']['App']['UpdateNamespaceYAML'](arg1, arg2);
}

export function UpdateNodeYaml(arg1, arg2) {
  return window['go']['main']['App']['UpdateNodeYaml'](arg1, arg2);
}

export function UpdatePVCYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePVCYaml'](arg1, arg2, arg3);
}

export function UpdatePVYaml(arg1, arg2) {
  return window['go']['main']['App']['UpdatePVYaml'](arg1, arg2);
}

export function UpdatePodYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePodYaml'](arg1, arg2, arg3);
}

export function UpdateReplicaSetYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateReplicaSetYaml'](arg1, arg2, arg3);
}

export function UpdateSecretData(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSecretData'](arg1, arg2, arg3);
}

export function UpdateSecretYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSecretYaml'](arg1, arg2, arg3);
}

export function UpdateServiceYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateServiceYaml'](arg1, arg2, arg3);
}

export function UpdateStatefulSetYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateStatefulSetYaml'](arg1, arg2, arg3);
}

export function UpdateStorageClassYaml(arg1, arg2) {
  return window['go']['main']['App']['UpdateStorageClassYaml'](arg1, arg2);
}
