// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {v1} from '../models';

export function GetCurrentContext():Promise<string>;

export function GetPodLogs(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListConfigMaps(arg1:string):Promise<Array<v1.ConfigMap>>;

export function ListContexts():Promise<Array<string>>;

export function ListDeployments(arg1:string):Promise<Array<v1.Deployment>>;

export function ListNamespaces():Promise<Array<v1.Namespace>>;

export function ListNodes():Promise<Array<v1.Node>>;

export function ListPods(arg1:string):Promise<Array<v1.Pod>>;

export function ListSecrets(arg1:string):Promise<Array<v1.Secret>>;

export function ListServices(arg1:string):Promise<Array<v1.Service>>;

export function SwitchContext(arg1:string):Promise<void>;
