// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {v1} from '../models';
import {main} from '../models';

export function DeleteConfigMap(arg1:string,arg2:string):Promise<void>;

export function DeleteCronJob(arg1:string,arg2:string):Promise<void>;

export function DeleteDaemonSet(arg1:string,arg2:string):Promise<void>;

export function DeleteDeployment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteJob(arg1:string,arg2:string):Promise<void>;

export function DeleteNamespace(arg1:string):Promise<void>;

export function DeletePod(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteReplicaSet(arg1:string,arg2:string):Promise<void>;

export function DeleteSecret(arg1:string,arg2:string):Promise<void>;

export function DeleteStatefulSet(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ForceDeletePod(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAllPodLogs(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function GetConfigMapYaml(arg1:string,arg2:string):Promise<string>;

export function GetCronJobYaml(arg1:string,arg2:string):Promise<string>;

export function GetCurrentContext():Promise<string>;

export function GetDaemonSetYaml(arg1:string,arg2:string):Promise<string>;

export function GetDeploymentYaml(arg1:string,arg2:string):Promise<string>;

export function GetJobYaml(arg1:string,arg2:string):Promise<string>;

export function GetNamespaceYAML(arg1:string):Promise<string>;

export function GetPodLogs(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function GetPodYaml(arg1:string,arg2:string):Promise<string>;

export function GetReplicaSetYaml(arg1:string,arg2:string):Promise<string>;

export function GetSecretData(arg1:string,arg2:string):Promise<Record<string, string>>;

export function GetSecretYaml(arg1:string,arg2:string):Promise<string>;

export function GetStatefulSetYaml(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListConfigMaps(arg1:string):Promise<Array<v1.ConfigMap>>;

export function ListContexts():Promise<Array<string>>;

export function ListCronJobs(arg1:string):Promise<Array<v1.CronJob>>;

export function ListDaemonSets(arg1:string):Promise<Array<v1.DaemonSet>>;

export function ListDeployments(arg1:string):Promise<Array<v1.Deployment>>;

export function ListJobs(arg1:string):Promise<Array<v1.Job>>;

export function ListNamespaces():Promise<Array<v1.Namespace>>;

export function ListNodes():Promise<Array<v1.Node>>;

export function ListPods(arg1:string):Promise<Array<v1.Pod>>;

export function ListReplicaSets(arg1:string):Promise<Array<v1.ReplicaSet>>;

export function ListSecrets(arg1:string):Promise<Array<v1.Secret>>;

export function ListServices(arg1:string):Promise<Array<v1.Service>>;

export function ListStatefulSets(arg1:string,arg2:string):Promise<Array<v1.StatefulSet>>;

export function LogDebug(arg1:string,arg2:Array<any>):Promise<void>;

export function OpenTerminal(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function RestartDaemonSet(arg1:string,arg2:string):Promise<void>;

export function RestartDeployment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestartStatefulSet(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveLogFile(arg1:string):Promise<void>;

export function SaveLogsBundle(arg1:Array<main.PodLogEntry>,arg2:string):Promise<void>;

export function SavePodLogs(arg1:string,arg2:string):Promise<void>;

export function StartPodWatcher(arg1:string):Promise<void>;

export function SuspendCronJob(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SwitchContext(arg1:string):Promise<void>;

export function TestEmit():Promise<void>;

export function TriggerCronJob(arg1:string,arg2:string):Promise<void>;

export function UpdateConfigMapYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateCronJobYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateDaemonSetYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateDeploymentYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateJobYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateNamespaceYAML(arg1:string,arg2:string):Promise<void>;

export function UpdatePodYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateReplicaSetYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateSecretData(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function UpdateSecretYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateStatefulSetYaml(arg1:string,arg2:string,arg3:string):Promise<void>;
