// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConfigMap(arg1, arg2) {
  return window['go']['main']['App']['DeleteConfigMap'](arg1, arg2);
}

export function DeleteDeployment(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteDeployment'](arg1, arg2, arg3);
}

export function DeletePod(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeletePod'](arg1, arg2, arg3);
}

export function DeleteSecret(arg1, arg2) {
  return window['go']['main']['App']['DeleteSecret'](arg1, arg2);
}

export function DeleteStatefulSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteStatefulSet'](arg1, arg2, arg3);
}

export function ForceDeletePod(arg1, arg2, arg3) {
  return window['go']['main']['App']['ForceDeletePod'](arg1, arg2, arg3);
}

export function GetConfigMapYaml(arg1, arg2) {
  return window['go']['main']['App']['GetConfigMapYaml'](arg1, arg2);
}

export function GetCurrentContext() {
  return window['go']['main']['App']['GetCurrentContext']();
}

export function GetDeploymentYaml(arg1, arg2) {
  return window['go']['main']['App']['GetDeploymentYaml'](arg1, arg2);
}

export function GetPodLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPodLogs'](arg1, arg2, arg3);
}

export function GetPodYaml(arg1, arg2) {
  return window['go']['main']['App']['GetPodYaml'](arg1, arg2);
}

export function GetSecretYaml(arg1, arg2) {
  return window['go']['main']['App']['GetSecretYaml'](arg1, arg2);
}

export function GetStatefulSetYaml(arg1, arg2) {
  return window['go']['main']['App']['GetStatefulSetYaml'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListConfigMaps(arg1) {
  return window['go']['main']['App']['ListConfigMaps'](arg1);
}

export function ListContexts() {
  return window['go']['main']['App']['ListContexts']();
}

export function ListDeployments(arg1) {
  return window['go']['main']['App']['ListDeployments'](arg1);
}

export function ListNamespaces() {
  return window['go']['main']['App']['ListNamespaces']();
}

export function ListNodes() {
  return window['go']['main']['App']['ListNodes']();
}

export function ListPods(arg1) {
  return window['go']['main']['App']['ListPods'](arg1);
}

export function ListSecrets(arg1) {
  return window['go']['main']['App']['ListSecrets'](arg1);
}

export function ListServices(arg1) {
  return window['go']['main']['App']['ListServices'](arg1);
}

export function ListStatefulSets(arg1, arg2) {
  return window['go']['main']['App']['ListStatefulSets'](arg1, arg2);
}

export function LogDebug(arg1, arg2) {
  return window['go']['main']['App']['LogDebug'](arg1, arg2);
}

export function OpenTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenTerminal'](arg1, arg2, arg3, arg4);
}

export function RestartDeployment(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestartDeployment'](arg1, arg2, arg3);
}

export function RestartStatefulSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestartStatefulSet'](arg1, arg2, arg3);
}

export function StartPodWatcher(arg1) {
  return window['go']['main']['App']['StartPodWatcher'](arg1);
}

export function SwitchContext(arg1) {
  return window['go']['main']['App']['SwitchContext'](arg1);
}

export function TestEmit() {
  return window['go']['main']['App']['TestEmit']();
}

export function UpdateConfigMapYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConfigMapYaml'](arg1, arg2, arg3);
}

export function UpdateDeploymentYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDeploymentYaml'](arg1, arg2, arg3);
}

export function UpdatePodYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePodYaml'](arg1, arg2, arg3);
}

export function UpdateSecretYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSecretYaml'](arg1, arg2, arg3);
}

export function UpdateStatefulSetYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateStatefulSetYaml'](arg1, arg2, arg3);
}
