// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {k8s} from '../models';
import {helm} from '../models';
import {v1} from '../models';
import {v2} from '../models';

export function AddHelmRepository(arg1:string,arg2:string,arg3:number):Promise<void>;

export function AddPortForwardConfig(arg1:main.PortForwardConfig):Promise<main.PortForwardConfig>;

export function CollectIngressHostnames(arg1:Array<string>):Promise<Array<string>>;

export function CreateNodeDebugPod(arg1:string):Promise<main.NodeDebugPodResult>;

export function DeleteCRD(arg1:string):Promise<void>;

export function DeleteCSIDriver(arg1:string):Promise<void>;

export function DeleteCSINode(arg1:string):Promise<void>;

export function DeleteClusterRole(arg1:string):Promise<void>;

export function DeleteClusterRoleBinding(arg1:string):Promise<void>;

export function DeleteConfigMap(arg1:string,arg2:string):Promise<void>;

export function DeleteCronJob(arg1:string,arg2:string):Promise<void>;

export function DeleteCustomResource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DeleteDaemonSet(arg1:string,arg2:string):Promise<void>;

export function DeleteDeployment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteEndpoints(arg1:string,arg2:string):Promise<void>;

export function DeleteEvent(arg1:string,arg2:string):Promise<void>;

export function DeleteHPA(arg1:string,arg2:string):Promise<void>;

export function DeleteIngress(arg1:string,arg2:string):Promise<void>;

export function DeleteIngressClass(arg1:string):Promise<void>;

export function DeleteJob(arg1:string,arg2:string):Promise<void>;

export function DeleteLease(arg1:string,arg2:string):Promise<void>;

export function DeleteLimitRange(arg1:string,arg2:string):Promise<void>;

export function DeleteMutatingWebhookConfiguration(arg1:string):Promise<void>;

export function DeleteNamespace(arg1:string):Promise<void>;

export function DeleteNetworkPolicy(arg1:string,arg2:string):Promise<void>;

export function DeleteNode(arg1:string):Promise<void>;

export function DeletePDB(arg1:string,arg2:string):Promise<void>;

export function DeletePV(arg1:string):Promise<void>;

export function DeletePVC(arg1:string,arg2:string):Promise<void>;

export function DeletePod(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeletePortForwardConfig(arg1:string):Promise<void>;

export function DeletePriorityClass(arg1:string):Promise<void>;

export function DeleteReplicaSet(arg1:string,arg2:string):Promise<void>;

export function DeleteResourceQuota(arg1:string,arg2:string):Promise<void>;

export function DeleteRole(arg1:string,arg2:string):Promise<void>;

export function DeleteRoleBinding(arg1:string,arg2:string):Promise<void>;

export function DeleteSecret(arg1:string,arg2:string):Promise<void>;

export function DeleteService(arg1:string,arg2:string):Promise<void>;

export function DeleteServiceAccount(arg1:string,arg2:string):Promise<void>;

export function DeleteStatefulSet(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteStorageClass(arg1:string):Promise<void>;

export function DeleteValidatingWebhookConfiguration(arg1:string):Promise<void>;

export function DetectIngressController():Promise<main.IngressController>;

export function ExpandDependencyNode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<k8s.DependencyGraph>;

export function ForceDeletePod(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ForceHelmReleaseStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetActivePortForwards():Promise<Array<main.ActivePortForward>>;

export function GetAllPodLogs(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<string>;

export function GetAvailablePort(arg1:number):Promise<number>;

export function GetCRDPrinterColumns(arg1:string):Promise<Array<k8s.PrinterColumn>>;

export function GetCRDYaml(arg1:string):Promise<string>;

export function GetCSIDriverYaml(arg1:string):Promise<string>;

export function GetCSINodeYaml(arg1:string):Promise<string>;

export function GetClusterRoleBindingYaml(arg1:string):Promise<string>;

export function GetClusterRoleYaml(arg1:string):Promise<string>;

export function GetConfigMapYaml(arg1:string,arg2:string):Promise<string>;

export function GetCronJobYaml(arg1:string,arg2:string):Promise<string>;

export function GetCurrentContext():Promise<string>;

export function GetCustomResourceYaml(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function GetDaemonSetYaml(arg1:string,arg2:string):Promise<string>;

export function GetDeploymentYaml(arg1:string,arg2:string):Promise<string>;

export function GetEndpointsYaml(arg1:string,arg2:string):Promise<string>;

export function GetEventYAML(arg1:string,arg2:string):Promise<string>;

export function GetHPAYaml(arg1:string,arg2:string):Promise<string>;

export function GetHelmChartVersions(arg1:string,arg2:string):Promise<Array<helm.ChartVersion>>;

export function GetHelmRelease(arg1:string,arg2:string):Promise<helm.ReleaseDetail>;

export function GetHelmReleaseAllValues(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetHelmReleaseHistory(arg1:string,arg2:string):Promise<Array<helm.ReleaseHistory>>;

export function GetHelmReleaseResources(arg1:string,arg2:string):Promise<Array<helm.ResourceReference>>;

export function GetHelmReleaseValues(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetIngressClassYaml(arg1:string):Promise<string>;

export function GetIngressForwardState():Promise<main.IngressForwardState>;

export function GetIngressYaml(arg1:string,arg2:string):Promise<string>;

export function GetJobYaml(arg1:string,arg2:string):Promise<string>;

export function GetLeaseYaml(arg1:string,arg2:string):Promise<string>;

export function GetLimitRangeYaml(arg1:string,arg2:string):Promise<string>;

export function GetManagedHosts():Promise<Array<string>>;

export function GetMutatingWebhookConfigurationYaml(arg1:string):Promise<string>;

export function GetNamespaceResourceCounts(arg1:string):Promise<k8s.NamespaceResourceCounts>;

export function GetNamespaceYAML(arg1:string):Promise<string>;

export function GetNetworkPolicyYaml(arg1:string,arg2:string):Promise<string>;

export function GetNodeMetrics():Promise<k8s.NodeMetricsResult>;

export function GetNodeYaml(arg1:string):Promise<string>;

export function GetPDBYaml(arg1:string,arg2:string):Promise<string>;

export function GetPVCYaml(arg1:string,arg2:string):Promise<string>;

export function GetPVYaml(arg1:string):Promise<string>;

export function GetPodLogs(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:string):Promise<string>;

export function GetPodLogsAfter(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:string,arg7:number):Promise<main.LogChunkResult>;

export function GetPodLogsBefore(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:string,arg7:number):Promise<main.LogChunkResult>;

export function GetPodLogsFromStart(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<string>;

export function GetPodMetrics():Promise<k8s.PodMetricsResult>;

export function GetPodPorts(arg1:string,arg2:string):Promise<Array<number>>;

export function GetPodYaml(arg1:string,arg2:string):Promise<string>;

export function GetPortForwardConfigs(arg1:string):Promise<Array<main.PortForwardConfig>>;

export function GetPriorityClassYaml(arg1:string):Promise<string>;

export function GetRandomAvailablePort():Promise<number>;

export function GetReplicaSetYaml(arg1:string,arg2:string):Promise<string>;

export function GetResourceDependencies(arg1:string,arg2:string,arg3:string):Promise<k8s.DependencyGraph>;

export function GetResourceQuotaYaml(arg1:string,arg2:string):Promise<string>;

export function GetRoleBindingYaml(arg1:string,arg2:string):Promise<string>;

export function GetRoleYaml(arg1:string,arg2:string):Promise<string>;

export function GetSecretData(arg1:string,arg2:string):Promise<Record<string, string>>;

export function GetSecretYaml(arg1:string,arg2:string):Promise<string>;

export function GetServiceAccountYaml(arg1:string,arg2:string):Promise<string>;

export function GetServicePorts(arg1:string,arg2:string):Promise<Array<number>>;

export function GetServiceYaml(arg1:string,arg2:string):Promise<string>;

export function GetStatefulSetYaml(arg1:string,arg2:string):Promise<string>;

export function GetStorageClass(arg1:string):Promise<v1.StorageClass>;

export function GetStorageClassYaml(arg1:string):Promise<string>;

export function GetValidatingWebhookConfigurationYaml(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListCRDs():Promise<Array<v1.CustomResourceDefinition>>;

export function ListCSIDrivers():Promise<Array<v1.CSIDriver>>;

export function ListCSINodes():Promise<Array<v1.CSINode>>;

export function ListChartSources():Promise<Array<helm.ChartSourceInfo>>;

export function ListClusterRoleBindings():Promise<Array<v1.ClusterRoleBinding>>;

export function ListClusterRoles():Promise<Array<v1.ClusterRole>>;

export function ListConfigMaps(arg1:string):Promise<Array<v1.ConfigMap>>;

export function ListContexts():Promise<Array<string>>;

export function ListCronJobs(arg1:string):Promise<Array<v1.CronJob>>;

export function ListCustomResources(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<Record<string, any>>>;

export function ListDaemonSets(arg1:string):Promise<Array<v1.DaemonSet>>;

export function ListDeployments(arg1:string):Promise<Array<v1.Deployment>>;

export function ListEndpoints(arg1:string):Promise<Array<v1.Endpoints>>;

export function ListEvents(arg1:string):Promise<Array<v1.Event>>;

export function ListHPAs(arg1:string):Promise<Array<v2.HorizontalPodAutoscaler>>;

export function ListHelmReleases(arg1:Array<string>):Promise<Array<helm.Release>>;

export function ListHelmRepositories():Promise<Array<helm.Repository>>;

export function ListIngressClasses():Promise<Array<v1.IngressClass>>;

export function ListIngresses(arg1:string):Promise<Array<v1.Ingress>>;

export function ListJobs(arg1:string):Promise<Array<v1.Job>>;

export function ListLeases(arg1:string):Promise<Array<v1.Lease>>;

export function ListLimitRanges(arg1:string):Promise<Array<v1.LimitRange>>;

export function ListMutatingWebhookConfigurations():Promise<Array<v1.MutatingWebhookConfiguration>>;

export function ListNamespaces():Promise<Array<v1.Namespace>>;

export function ListNetworkPolicies(arg1:string):Promise<Array<v1.NetworkPolicy>>;

export function ListNodes():Promise<Array<v1.Node>>;

export function ListOCIRegistries():Promise<Array<helm.OCIRegistry>>;

export function ListPDBs(arg1:string):Promise<Array<v1.PodDisruptionBudget>>;

export function ListPVCs(arg1:string):Promise<Array<v1.PersistentVolumeClaim>>;

export function ListPVs():Promise<Array<v1.PersistentVolume>>;

export function ListPods(arg1:string):Promise<Array<v1.Pod>>;

export function ListPriorityClasses():Promise<Array<v1.PriorityClass>>;

export function ListReplicaSets(arg1:string):Promise<Array<v1.ReplicaSet>>;

export function ListResourceQuotas(arg1:string):Promise<Array<v1.ResourceQuota>>;

export function ListRoleBindings(arg1:string):Promise<Array<v1.RoleBinding>>;

export function ListRoles(arg1:string):Promise<Array<v1.Role>>;

export function ListSecrets(arg1:string):Promise<Array<v1.Secret>>;

export function ListServiceAccounts(arg1:string):Promise<Array<v1.ServiceAccount>>;

export function ListServices(arg1:string):Promise<Array<v1.Service>>;

export function ListStatefulSets(arg1:string,arg2:string):Promise<Array<v1.StatefulSet>>;

export function ListStorageClasses():Promise<Array<v1.StorageClass>>;

export function ListValidatingWebhookConfigurations():Promise<Array<v1.ValidatingWebhookConfiguration>>;

export function LogDebug(arg1:string,arg2:Array<any>):Promise<void>;

export function LoginACRWithAzureCLI(arg1:string):Promise<void>;

export function LoginOCIRegistry(arg1:string,arg2:string,arg3:string):Promise<void>;

export function LogoutOCIRegistry(arg1:string):Promise<void>;

export function OpenTerminal(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function OpenTerminalWithCommand(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function RefreshIngressHostnames(arg1:Array<string>):Promise<void>;

export function RemoveHelmRepository(arg1:string):Promise<void>;

export function RemoveOCIRegistry(arg1:string):Promise<void>;

export function ResizePVC(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestartDaemonSet(arg1:string,arg2:string):Promise<void>;

export function RestartDeployment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestartStatefulSet(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RollbackHelmRelease(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SaveLogFile(arg1:string):Promise<void>;

export function SaveLogsBundle(arg1:Array<main.PodLogEntry>,arg2:string):Promise<void>;

export function SavePodLogs(arg1:string,arg2:string):Promise<void>;

export function SaveYamlBackup(arg1:Array<main.YamlBackupEntry>,arg2:string):Promise<void>;

export function SearchChartInSource(arg1:string,arg2:string):Promise<helm.ChartSearchResult>;

export function SearchHelmChart(arg1:string):Promise<Array<helm.ChartSource>>;

export function SetHelmRepositoryPriority(arg1:string,arg2:number):Promise<void>;

export function SetNodeSchedulable(arg1:string,arg2:boolean):Promise<void>;

export function SetOCIRegistryPriority(arg1:string,arg2:number):Promise<void>;

export function StartFavoritePortForwards(arg1:string):Promise<void>;

export function StartIngressForward(arg1:main.IngressController,arg2:Array<string>):Promise<void>;

export function StartLogStream(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function StartPortForward(arg1:string):Promise<void>;

export function StartPortForwardsWithMode(arg1:string,arg2:string):Promise<void>;

export function StopAllPortForwards():Promise<void>;

export function StopAllWatchers():Promise<void>;

export function StopIngressForward():Promise<void>;

export function StopLogStream(arg1:string):Promise<void>;

export function StopPortForward(arg1:string):Promise<void>;

export function SubscribeCRDWatcher(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SubscribeResourceWatcher(arg1:string,arg2:string):Promise<string>;

export function SuspendCronJob(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SwitchContext(arg1:string):Promise<void>;

export function TestEmit():Promise<void>;

export function TriggerCronJob(arg1:string,arg2:string):Promise<void>;

export function UninstallHelmRelease(arg1:string,arg2:string):Promise<void>;

export function UnsubscribeWatcher(arg1:string):Promise<void>;

export function UpdateAllHelmRepositories():Promise<void>;

export function UpdateCRDYaml(arg1:string,arg2:string):Promise<void>;

export function UpdateCSIDriverYaml(arg1:string,arg2:string):Promise<void>;

export function UpdateCSINodeYaml(arg1:string,arg2:string):Promise<void>;

export function UpdateClusterRoleBindingYaml(arg1:string,arg2:string):Promise<void>;

export function UpdateClusterRoleYaml(arg1:string,arg2:string):Promise<void>;

export function UpdateConfigMapYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateCronJobYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateCustomResourceYaml(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function UpdateDaemonSetYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateDeploymentYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateEndpointsYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateEventYAML(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateHPAYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateHelmRepository(arg1:string):Promise<void>;

export function UpdateIngressClassYaml(arg1:string,arg2:string):Promise<void>;

export function UpdateIngressYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateJobYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateLeaseYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateLimitRangeYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateMutatingWebhookConfigurationYaml(arg1:string,arg2:string):Promise<void>;

export function UpdateNamespaceYAML(arg1:string,arg2:string):Promise<void>;

export function UpdateNetworkPolicyYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateNodeYaml(arg1:string,arg2:string):Promise<void>;

export function UpdatePDBYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdatePVCYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdatePVYaml(arg1:string,arg2:string):Promise<void>;

export function UpdatePodYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdatePortForwardConfig(arg1:main.PortForwardConfig):Promise<void>;

export function UpdatePriorityClassYaml(arg1:string,arg2:string):Promise<void>;

export function UpdateReplicaSetYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateResourceQuotaYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateRoleBindingYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateRoleYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateSecretData(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function UpdateSecretYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateServiceAccountYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateServiceYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateStatefulSetYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateStorageClassYaml(arg1:string,arg2:string):Promise<void>;

export function UpdateValidatingWebhookConfigurationYaml(arg1:string,arg2:string):Promise<void>;

export function UpgradeHelmRelease(arg1:string,arg2:string,arg3:helm.UpgradeOptions):Promise<void>;
