// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentContext() {
  return window['go']['main']['App']['GetCurrentContext']();
}

export function GetPodLogs(arg1, arg2) {
  return window['go']['main']['App']['GetPodLogs'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListConfigMaps(arg1) {
  return window['go']['main']['App']['ListConfigMaps'](arg1);
}

export function ListContexts() {
  return window['go']['main']['App']['ListContexts']();
}

export function ListDeployments(arg1) {
  return window['go']['main']['App']['ListDeployments'](arg1);
}

export function ListNamespaces() {
  return window['go']['main']['App']['ListNamespaces']();
}

export function ListNodes() {
  return window['go']['main']['App']['ListNodes']();
}

export function ListPods(arg1) {
  return window['go']['main']['App']['ListPods'](arg1);
}

export function ListSecrets(arg1) {
  return window['go']['main']['App']['ListSecrets'](arg1);
}

export function ListServices(arg1) {
  return window['go']['main']['App']['ListServices'](arg1);
}

export function SwitchContext(arg1) {
  return window['go']['main']['App']['SwitchContext'](arg1);
}
