name: PR

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      publish: false
      build_version: v0.0.0
